### ISSUE TITLE
Add direct mapping for quality related options

### ISSUE THREAD

**Issue by slhck** [slhck/ffmpeg-normalize#101]
Add an option for -q:a and similar.

**Comment by putnam** [comment]
Probably should be a separate issue, but while the output options are handy, it would be nice to also have input-side options. I normalized a bunch of ancient mpg files that needed -fflags +genpts set for them, which was not possible without patching ffmpeg-normalize.

**Comment by slhck** [comment]
Yes, that could be done, but these would again apply to all input files, and it'd have to be quite generic since I couldn't possibly map all existing ffmpeg options. But I'll have a look.

**Comment by putnam** [comment]
Yeah I would imagine it would work just like the --extra-output-options param. Same deal, arbitrary string that gets inserted before -i.

**Comment by slhck** [comment]
This has been released in v1.20.0 via the `-ei`/`--extra-input-options` option.
