### ISSUE TITLE
Frequencies above 18khz get clipped

### ISSUE THREAD

**Issue by mmehrle** [slhck/ffmpeg-normalize#102]
I've run a few clips through ffmpeg-normalize via this command:
ffmpeg-normalize *.MP4 -pr -of ./ -ext wav

When dragging the output into iZotope it seems that all frequencies above 18khz have been clipped. 

Here's the source clip before ffmpeg-normalize in iZotope:

![2019-06-10_before](https://user-images.githubusercontent.com/8457499/59211321-e04a1580-8baf-11e9-8046-9ddef4ea5639.png)

Here it is after normalizing:

![2019-06-10_after](https://user-images.githubusercontent.com/8457499/59211372-f7890300-8baf-11e9-9f52-23113466eb37.png)

**Comment by slhck** [comment]
Can you reproduce this with a simple loudnorm call? This seems like an upstream bug.

And just to make sure, you're using PCM audio encoding?

**Comment by mmehrle** [comment]
Here's ffmpeg's info for the source MP4:

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'MVI_0678.MP4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp42avc1CAEP
    make            : 
    make-eng        : 
    model           : 
    model-eng       : 
    creation_time   : 2018-11-29T14:06:59.000000Z
  Duration: 00:01:53.91, start: 0.000000, bitrate: 28580 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 1920x1080, 28292 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 48k tbc (default)
    Metadata:
      creation_time   : 2018-11-29T14:06:59.000000Z
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 255 kb/s (default)
    Metadata:
      creation_time   : 2018-11-29T14:06:59.000000Z

After that I ran this from the command line:

ffmpeg-normalize MVI_0678.MP4 -pr -of ./ -ext wav

Which produced the audio clip with the clipped frequencies.

**Comment by slhck** [comment]
As mentioned above, please run a “normal” loudnorm conversion with ffmpeg:

```
ffmpeg -i MVI_0678.MP4 -vn -af loudnorm -c:a pcm_s16le output.wav
```

Does the output have the same problem?

**Comment by mmehrle** [comment]
Thanks for the quick input Werner - much obliged. Okay I ran the loudnorm conversion as instructed in your previous comment. Dragged the output into iZotope and took a screenshot:

![2019-06-11_1128](https://user-images.githubusercontent.com/8457499/59260683-56945980-8c3c-11e9-8577-5d31721a26de.png)

Seems to me that frequencies above 18khz are being clipped. Not a problem for speech but for music it would be.

**Comment by slhck** [comment]
Perhaps I'm reading the charts wrong (I had previously only seen them on a mobile and assumed that you'd checked them), but looking at the graphs again, I don't see the clipping.

![image](https://user-images.githubusercontent.com/582444/59264189-da514480-8c42-11e9-9328-6b2eace407f4.png)

If this is the orignal, you can see almost no frequencies above 18K anyway. The output file then shows a similar spectrum with the same cutoff, just at a different overall level.

**Comment by mmehrle** [comment]
Here's the original - dragged the MP4 file directly into iZotope:

![2019-06-11_before](https://user-images.githubusercontent.com/8457499/59267669-1688a300-8c4b-11e9-92b4-31cd205b9e49.png)

It's pretty clear to me and if you analyze any converted output on your end then you'll see that everything > 18khz appear to be clipped. Have you run a pertinent test?

**Comment by slhck** [comment]
Observing the orange parts of the plots, you'll notice that the loudness range is just “squeezed” but the overall spectrum (including its cutoff) stays the same. The y-axis isn't on the same scale, so one might believe that the frequency range is lower.

But I don't know what you mean by “read differently”? Or what “frequency range that is not in the file” are you talking about?

(I am ignoring the blue waveform display now … not sure how to interpret it in the context of this visualization.)
