### ISSUE TITLE
Q: Merge data back to original file / Preserving original metadata

### ISSUE THREAD

**Issue by X-Raym** [slhck/ffmpeg-normalize#107]
Hi !

it seems that previous versions of ffmpeg-normalize have --merge -u parmater to merge noralized data back to original file.
This allows to keep all metdata the same. Metadata aren't preserved with ffmpeg-normalize. (some are even converted to LIST INFO rather than staying in bext).

Is there a way to merge data to original file ?
Or to keep all original metadata ?

Thx !

**Comment by slhck** [comment]
This parameter does not exist anymore; it was a bit clumsily implemented.

Now, by default, all the ffmpeg options for preserving metadata are enabled, but I can't promise that ffmpeg-normalize doesn't do anything weird when reading/writing those.

The easiest would be to normalize the file and merge it manually. Are you sure that manually merging back into the original preserves everything? Do you have a sample to test with?

**Comment by X-Raym** [comment]
> but I can't promise that ffmpeg doesn't do anything weird when reading/writing those.

Well, it does do weird things like converting BWF to LIST-INFO. This can lead to metadata errors as not all characters are allowed.

> Are you sure that manually merging back into the original preserves everything?

Well, I can only speak for wavefile which has constant bitrate. Unless I miss something, taking data chunk from one wav file to another if they have same bit depth should work I guess. But if they have different sample rate, adjustment have to be made in FMT (as the size of the wave file is declared there).

I made a wav file parser which handle more chunks https://github.com/X-Raym/wavfile.py It was a long time ago so I don't know if it is relevant, but it can be a good place to start to mess with chunks.
So maybe a companion script to push metdata from file 1 to file 2 could be made from that.
But this would be only for wav files, and I think this library has a broader scope.

Note that from a performance point of view, it will be better to take metadata chunk from first file and put them in the new one than the opposite, as data chunk can be several gigas, which is quite unlikely with metadata.

**Comment by slhck** [comment]
As I mentioned above, it would be best if you had an example with which we can inspect what is going on.

Note that there is a difference between coded bitstreams (e.g. PCM audio) and containers (e.g. WAV), so this shouldn't really be about bit depth or sample rate, right? I guess the issue is that when you take an input file `input.wav` and convert it to an output file `output.wav` with `ffmpeg`, it'll “do something” with broadcast WAV or LIST-INFO metadata? This would essentially be an upstream ffmpeg issue.

**Comment by X-Raym** [comment]
@slhck Here is source file

https://drive.google.com/file/d/1Zo7uJIEiebm-O0y_AoocDvFFbfqH_-ae/view?usp=sharing

Command line used:

`for %%f in ("*.WAV") do ffmpeg-normalize "%%f" -c:a pcm_s24le -ext wav --sample-rate 96000`

As you can see you BWFMetaEdit screenshots below, BWF have been stripped

![Image](https://i.imgur.com/r4Skyrq.png)

Some infos have been pushed as LIST-INFO. But some are invalid.

![image](https://i.imgur.com/MsHRNXV.png)

I can use `-mn` to strip metadata but it doesnt strip ISFT for some reason.

**Comment by slhck** [comment]
I can reproduce this, but even by simply doing 

    ffmpeg -i input.wav -c copy -map_metadata 0 output.wav

So this is an upstream bug or lack of feature. Please report on https://trac.ffmpeg.org/ if there are no similar issues.

**Comment by slhck** [comment]
According to [this thread](https://lists.ffmpeg.org/pipermail/ffmpeg-user/2015-April/026072.html), the muxer supports the bext chunk (with `-write_bext 1`) but not the metadata.

**Comment by X-Raym** [comment]
@slhck Thanks for your investigation ! so this is ffmepg bug (bug cause it do introduce wrong data as LIST INFO). I will consider to report it then, and inspect your workarround.
Best,

**Comment by X-Raym** [comment]
@shlck though, you can see the benefit of merging data back to original file :P

**Comment by slhck** [comment]
Though this kind of “merging” cannot be done with ffmpeg, since it'll always read the file entirely and write a new one, losing the metadata in the process.
