### ISSUE TITLE
Question: Can I use ffmpeg-normalize in an ffmpeg command line?

### ISSUE THREAD

**Issue by TrevorAyl** [slhck/ffmpeg-normalize#111]
e.g. Can I pipe or incorporate ffmpeg-normalize in the following?

ffmpeg -i INPUTFILE -ss 00:00:00 -t 00:00:10 -vf 'split[original][copy];[copy]scale=ih*21/9:-1,crop=h=iw*9/21,gblur=sigma=50[blurred];[original]scale=ih*0.8:-1,drawbox=c=red:t=10[original_with_box];[blurred][original_with_box]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2' OUTPUTFILE

Thanks

**Comment by slhck** [comment]
No, that is not possible. ffmpeg-itself uses various ffmpeg CLI calls and filters.

You have two options:

1. Process the audio separately and copy it back into the video
2. Use the `loudnorm` filter in ffmpeg directly (ideally though with two passes, which requires a bit more parsing/scripting, hence this project)
