### ISSUE TITLE
Normalizing audio with iTunSMPB

### ISSUE THREAD

**Issue by prashantkukde** [slhck/ffmpeg-normalize#114]
**Expected behavior**
Thanks for the ffmpeg-normalize utility. I am processing some m4a files with iTunSMPB in it. The output of 
```ffmpeg -i input.m4a```  is as follows,
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'input.m4a':
  Metadata:
    major_brand     : M4A 
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2019-06-25T17:44:24.000000Z
    **iTunSMPB        :  00000000 00000840 00000000 00000000033E3BC0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000**
  Duration: 00:20:33.79, start: 0.047891, bitrate: 306 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 305 kb/s (default)
    Metadata:
      creation_time   : 2019-06-25T17:44:24.000000Z
      handler_name    : Core Media Audio
```
Same output on Ubuntu or Debian. 

I notice RMS normalization for the m4a files with iTunSMPB is not great as compared to the files without iTunSMPB. Following is my sample command for ffmpeg-normalize. 
```ffmpeg-normalize "input.m4a" -nt rms -t -28.0 -o "input-28rms.wav" ```

Anything I have to do for m4a files with iTunSMPB to perform RMS normalization? 

Thanks,
Prashant

**Comment by slhck** [comment]
What specifically do you mean by "not great"? Could you supply a sample file that exhibits the issue? That'd be great.

**Comment by ValZapod** [comment]
AFAIK, ffmpeg does not write iTunSMPB at all. So aac is not fully implemented. https://trac.ffmpeg.org/ticket/2325
