### ISSUE TITLE
Output audio in video with sound too short, no lipsync anymore

### ISSUE THREAD

**Issue by Chris56** [slhck/ffmpeg-normalize#115]
**Expected behavior**
ffmpeg-normalize v1.15.8
Keep lipsync in video file with oudio track

**Actual behavior**
Output is out of lipsync, because audio track is too short
See below:
video track: DURATION        : 00:00:24.526000000
audio track: DURATION        : 00:00:24.494000000
but then further down:
DEBUG: Found duration: 24.053 s
This is wrong !!!!!

The audio in the resulting output is 
Duration                                 : 24 s 69 ms
The video duration in the output is correct -> no lipsync anymore, because audio is shortened
from 24.494 to 24.069 
!!!

**Command**

```
~/.local/bin/ffmpeg-normalize -d -of normalized -nt ebu -c:a libmp3lame -b:a 192k output.mkv
```

Any output you get when running the command with the `--debug` flag:

```
...
Input #0, matroska,webm, from 'output.mkv':
  Metadata:
    COMPATIBLE_BRANDS: isommp42
    COM.ANDROID.VERSION: 10
    MAJOR_BRAND     : mp42
    MINOR_VERSION   : 0
    ENCODER         : Lavf57.83.100
  Duration: 00:00:24.53, start: 0.000000, bitrate: 4059 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
    Metadata:
      HANDLER_NAME    : VideoHandle
      ENCODER         : Lavc57.107.100 libx264
      DURATION        : 00:00:24.526000000
    Stream #0:1(eng): Audio: mp3, 48000 Hz, stereo, s16p, 192 kb/s (default)
    Metadata:
      HANDLER_NAME    : SoundHandle
      ENCODER         : Lavc57.107.100 libmp3lame
      DURATION        : 00:00:24.494000000
Output #0, null, to '/dev/null':
  Metadata:
    COMPATIBLE_BRANDS: isommp42
    COM.ANDROID.VERSION: 10
    MAJOR_BRAND     : mp42
    MINOR_VERSION   : 0
    encoder         : Lavf57.83.100
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      HANDLER_NAME    : VideoHandle
      ENCODER         : Lavc57.107.100 libx264
      DURATION        : 00:00:24.526000000
    Stream #0:1(eng): Audio: mp3, 48000 Hz, stereo, s16p, 192 kb/s (default)
    Metadata:
      HANDLER_NAME    : SoundHandle
      ENCODER         : Lavc57.107.100 libmp3lame
      DURATION        : 00:00:24.494000000
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    2 fps=0.0 q=-1.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
video:153kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

DEBUG: Found duration: 24.053 s
DEBUG: Found video stream at index 0
DEBUG: Found audio stream at index 1
...
```

**Environment (please complete the following information):**
- [Linux Mint 19.1 ] Your operating system
- [Python 3.6.9 ] Your Python version / distribution (`python --version`)
- [ffmpeg version 3.4.6-0ubuntu0.18.04.1 ] Your ffmpeg version (`ffmpeg -version`)

If you do not fill out this information, your bug report may be closed.

**Comment by slhck** [comment]
Thanks for reporting this. So I see that the duration is inferred from the container, and not the individual streams. Is the output simply cut off in the end, or is the complete audio out of sync?

**Comment by Chris56** [comment]
The time is NOT taken from the container, mediainfo of the original data says:
General
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42)
File size                                : 42.3 MiB
Duration                                 : 24 s 448 ms
Overall bit rate                         : 14.5 Mb/s
Encoded date                             : UTC 2020-02-09 17:51:38
Tagged date                              : UTC 2020-02-09 17:51:38
com.android.version                      : 10

Video
ID                                       : 2
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 1 frame
Format settings, GOP                     : M=1, N=30
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 24 s 438 ms
Bit rate                                 : 14.3 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 29.748 FPS
Minimum frame rate                       : 4.486 FPS
Maximum frame rate                       : 30.070 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.232
Stream size                              : 41.7 MiB (99%)
Title                                    : VideoHandle
Language                                 : English
Encoded date                             : UTC 2020-02-09 17:51:38
Tagged date                              : UTC 2020-02-09 17:51:38

Audio
ID                                       : 1
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 24 s 448 ms
Duration_FirstFrame                      : 448 ms
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 563 KiB (1%)
Title                                    : SoundHandle
Language                                 : English
Encoded date                             : UTC 2020-02-09 17:51:38
Tagged date                              : UTC 2020-02-09 17:51:38

So container duration is 24 s 448 ms
Video duration is 24 s 438 ms
Audio duration is 24 s 448 ms

Now when I do 
ffmpeg-normalize -d -of normalized -nt ebu -c:a libmp3lame -b:a 192k on the original data mediainfo on the resulting mkv is
General

Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 42.3 MiB
Duration                                 : 24 s 461 ms
Overall bit rate                         : 14.5 Mb/s
Encoded date                             : UTC 2020-02-09 17:51:38
Writing application                      : Lavf57.83.100
Writing library                          : Lavf57.83.100
ErrorDetectionType                       : Per level 1
COM.ANDROID.VERSION                      : 10

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 1 frame
Format settings, GOP                     : M=1, N=30
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 24 s 438 ms
Bit rate                                 : 14.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.748 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.227
Stream size                              : 40.8 MiB (97%)
Title                                    : VideoHandle
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo
Codec ID                                 : A_MPEG/L3
Codec ID/Hint                            : MP3
Duration                                 : 24 s 23 ms
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Delay relative to video                  : -23 ms
Stream size                              : 563 KiB (1%)
Title                                    : SoundHandle
Writing library                          : Lavc57.107.100 libmp3lame
Language                                 : English
Default                                  : Yes
Forced                                   : No

Note the
adio duration is  24 s 23 ms
No lipsync!

However, when I do
ffmpeg -i infile.mp4 -c:v copy -af "volume=-5.2dB" -c:a libmp3lame -b:a 192k outfile.mkv
I.e. the encoder is the same as with ffmpeg-normalize
The mediainfo of outfile is:
General

Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 42.3 MiB
Duration                                 : 24 s 471 ms
Overall bit rate                         : 14.5 Mb/s
Writing application                      : Lavf57.83.100
Writing library                          : Lavf57.83.100
ErrorDetectionType                       : Per level 1
COM.ANDROID.VERSION                      : 10

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 1 frame
Format settings, GOP                     : M=1, N=30
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 24 s 438 ms
Bit rate                                 : 14.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.748 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.227
Stream size                              : 40.8 MiB (97%)
Title                                    : VideoHandle
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo
Codec ID                                 : A_MPEG/L3
Codec ID/Hint                            : MP3
Duration                                 : 24 s 471 ms
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Delay relative to video                  : -23 ms
Stream size                              : 574 KiB (1%)
Title                                    : SoundHandle
Writing library                          : Lavc57.107.100 libmp3lame
Language                                 : English
Default                                  : Yes
Forced                                   : No

Note the
audio duration is 24 s 471 ms
Which is correct with lipsync!

**Comment by Chris56** [comment]
P.S: I can provide a url of the original data

**Comment by slhck** [comment]
That would be very helpful.

**Comment by Chris56** [comment]
The original data:
https://cloud.hemsing.eu/index.php/s/cgLWooPZEaL5Moq

**Comment by kostalski** [comment]
Hi @Chris56 ,

It is ffmpeg audio timing issue. For solving it please add `aresample=async=1` audio filter - this will automatically adjust start time for audio with video.

For fffmeg-normalize please use "pre-filter" option: `-prf 'aresample=async=1'`. I've checked it with your sample mp4 file and audio was synchronized with video correctly (lipsync was kept). Sample command line use:
`ffmpeg-normalize -prf 'aresample=async=1' -d -of normalized -f -nt ebu -c:a libmp3lame -b:a 192k sample.mp4`

In case of loosing audio/video synchronisation during later playback (lipsync kept on beginning, loosing at end) playing with `async` value is useful. Setting `async=1` solves problem with general audio shift. If audio is a bit shorter / longer than video setting `async=25` ( `-prf 'aresample=async=25'` ) should solve the problem. It would stretch/squeeze audio automatically for fitting to video length. 

I hope my comment helps.
