### ISSUE TITLE
Unix way! Supress all output unless there're errors

### ISSUE THREAD

**Issue by splitfront** [slhck/ffmpeg-normalize#116]
An option to supress all console output except error message would be useful — in accordance to classic Unix-y convention where lack of output means normal termination of script.

**Comment by slhck** [comment]
True. I have a `quiet` option in most of my other tools. For some reason it's missing here. Should be easy to add via the log levels: https://github.com/slhck/ffmpeg-normalize/blob/master/ffmpeg_normalize/__main__.py#L336

Will look into it soon.
