### ISSUE TITLE
Pre-filters which affect levels will render wrong result

### ISSUE THREAD

**Issue by weltonrodrigo** [slhck/ffmpeg-normalize#118]
**Expected behavior**
When using pre-filters, the output should render the proper loudness level.

**Actual behavior**
If you use a pre-filter capable of altering material or levels (silencing, compression, noise reduction, normalize, etc), they will not be taken in account when calculating loudness correction.

**Command**
The exact command you were trying to run:

```
ffmpeg-normalize -prf dynaudnorm inputfile -ext mp3 
```

I have submitted #117 to address that. Feel free to discard it if you disagree about the logic here.

**Comment by slhck** [comment]
True, any filter should actually be set in both passes to ensure correct leveling.

**Comment by slhck** [comment]
This is available in v1.17.0.
