### ISSUE TITLE
Follow-up to #119

### ISSUE THREAD

**Issue by grb43** [slhck/ffmpeg-normalize#120]
Wow, that was a prompt fix for #119.

However, I think the fix means the --output argument is effectively disabled. In this case the documentation is now wrong (since --output is not 0 by default and can't be set) and should be updated or removed?

**Comment by slhck** [comment]
It's not disabled, as it is still used for the first pass. The results from the first pass will then be used for the second pass. This is also how the author of the loudnorm filter has used it: https://github.com/FFmpeg/FFmpeg/blob/master/tools/loudnorm.rb

**Comment by grb43** [comment]
Yes, understood.

I was trying to point out that the --output argument no longer sets the Offset Gain used for the second pass. And setting the Offset Gain to anything other than 0 for the first pass probably has little application/value.

I felt you may have wanted to clarify the description of the --offset argument accordingly, or even deprecate it.

But no biggie, I appreciate your efforts.

**Comment by slhck** [comment]
Yeah, of course that could be clarified. Then again, even the filter documentation itself is not very easy to understand w.r.t. usage for one or two passes. Do you have a suggestion as to how it should be changed? For example:

> Please note that the option only applies to the first pass. The offset for the second pass will be automatically determined based on the first pass statistics.

**Comment by grb43** [comment]
I had a lot of trouble with the documentation as well, which is why I was interested to see how you were using it.

I thought your suggested wording was fine, but after having a quick play with some real examples, I'm starting to doubt that the option makes any sense now.

During the first pass, the loudnorm filter does take the offset gain setting into account. e.g. an :offset=2.0 produces different output than the default :offset=0.0. So the calculated target offset depends on the initial offset setting. But the initial offset is never applied to the second pass because it is reset automatically to the calculated target offset.

I think the only safe option is to ensure the first pass is always made with the default offset, zero. I note that the 2-pass example given by the author of the filter used the default.

Hope these comments help.

**Comment by slhck** [comment]
Thanks for your feedback. I guess though that this is how it is supposed to work, in the sense of always using the calculated target offset no matter what the initial offset was? (I begin to wonder in which cases it would even make sense to change the offset for the first pass.)

I want to keep the option since the filter also allows setting it, but I could print a warning when the value is changed. (Something like the above sentence.)

**Comment by greg-kennedy** [comment]
I know this is a very old issue but I find myself confused (again) by the "target_offset" / "offset gain" used throughout.

Looking at [the source for `af_loudnorm.c`](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/af_loudnorm.c#L906):
```c
    case SUMMARY:
        av_log(ctx, AV_LOG_INFO,
            "\n"
            "Input Integrated:   %+6.1f LUFS\n"
            "Input True Peak:    %+6.1f dBTP\n"
            "Input LRA:          %6.1f LU\n"
            "Input Threshold:    %+6.1f LUFS\n"
            "\n"
            "Output Integrated:  %+6.1f LUFS\n"
            "Output True Peak:   %+6.1f dBTP\n"
            "Output LRA:         %6.1f LU\n"
            "Output Threshold:   %+6.1f LUFS\n"
            "\n"
            "Normalization Type:   %s\n"
            "Target Offset:      %+6.1f LU\n",
            i_in,
            20. * log10(tp_in),
            lra_in,
            thresh_in,
            i_out,
            20. * log10(tp_out),
            lra_out,
            thresh_out,
            s->frame_type == LINEAR_MODE ? "Linear" : "Dynamic",
            s->target_i - i_out
        );
        break;
```

So: the "Target Offset" value is defined as **the difference between the `target_i` and the output `i` value**.

When running in single-pass `dynamic` mode, it's likely that the volume ramping done by the filter doesn't lead to a precisely correct match with the desired target... after all, the filter doesn't know the future and is making only a best-effort to keep the output near the target.  At the end of the process, poor prediction / inaccuracy may cause the filter to not match the desired LUFS target.  The difference between "what you wanted" and "what you got" is shown as the target_offset.  ("You wanted -24.0 but I only managed -23.57 this pass, an Offset of -0.43")

The purpose of the "offset" parameter is to apply pre-gain changes to the input stream, prior to peak limiting.  By default, it's 0.0.  But!  If you *know* there will be some inaccuracy, or you want to compress a bit, you can change this to something else.

Now, when running the second pass:
* If your second pass is also `dynamic`: You should set `offset` equal to the "Target offset" of pass 1.  Assuming the same input file, the same decisions are made for limiting etc. by the filter, and so you'd expect the same inaccuracy at the end of the command.  Setting `offset` corrects this by building in the difference at the start of the process, so everything comes out at 0.0 difference in the end.
* But!  if your second pass is `linear`: You should not change `offset` from zero at all.  The complete measurements given by the first pass are enough for the `linear` mode to precisely adjust the volume and leave no error, thus no up-front error correction needs specified.  Indeed I am testing with ffmpeg 6.1.2 and the same command with `offset=0` and `offset=10` give the exact same output - implying that either the value is ignored.

It seems there's no harm in setting the `offset` for linear, but it also doesn't do anything.

**Comment by slhck** [comment]
Thanks for the comment!

> If your second pass is also dynamic: You should set offset equal to the "Target offset" of pass 1

This is essentially what is automatically being done here: https://github.com/slhck/ffmpeg-normalize/blob/7edfe8ccf5c89c49f25fe3f99ad2ebc70ea47b9e/ffmpeg_normalize/_streams.py#L518

However, the same applies to linear mode.

Looking at this part of the filter: https://github.com/FFmpeg/FFmpeg/blob/1cead9029227614cb12a07e69d8823287ca980a0/libavfilter/af_loudnorm.c#L618

it seems that indeed the offset is applied first before processing.
