### ISSUE TITLE
Multiple input/output : output file path is wrong

### ISSUE THREAD

**Issue by depauwjimmy** [slhck/ffmpeg-normalize#121]
I have 2 audio files, first one remains the same while the other one is coming from recordings. They are concatenated later.
I wish the second audio files to be normalized in relation to the first one before merging them so there is no huge difference in volume between the 2.

So i want to use the 2 files as input and get 2 outputs.
This seems to be working but there is a problem with how output are written.

I use 

    ffmpeg-normalize input1.m4a input2.m4a -o F1.wav -o F2.wav

But the result is not the expected behavior.
- input1.m4a output is F2.wav
- input2.m4a output is ignored and fallback to default with normalized/input2.mkv

Thanks for your help

**Comment by slhck** [comment]
You're right, the docs were a bit unclear in that regard. You can only use `-o` once, so use `-o out1.wav out2.wav` etc.

I clarified the README and usage. I also introduced a warning that tells the user when too few output file names have been given for the number of input files. A new version v1.18.1 was released just now.
