### ISSUE TITLE
Is any limiting applied to prevent clipping when applying gain?

### ISSUE THREAD

**Issue by unfa** [slhck/ffmpeg-normalize#125]
I wonder if there's any measures taken to prevent signal clipping at 0dBFS when the loudness is being increased.

I've been searching for a commandline-usable way of normalizing my video's audio to -14 LUFS, but I couldn't do it with any good sounding results with SoX, so I'm seeking other tools.

**Comment by slhck** [comment]
Have you tried running `ffmpeg-normalize`? I believe it should work fine, as there is a true peak limiter in the `loudnorm` filter chain.

For a more in-depth explanation, see http://k.ylo.ph/2016/04/04/loudnorm.html
