### ISSUE TITLE
'Output file path does not exist' error

### ISSUE THREAD

**Issue by Yep101** [slhck/ffmpeg-normalize#126]
Hello, I'm new to FFmpeg-Normalize and I gave it a try today. 

What I wanted to do with the program is to normalize the mp3 files I have.

And tried to do it, following 'Description'.

**
ffmpeg-normalize chapter1.mp3 -c:a libmp3lame -b:a 320k -o chapter1_normalized.mp3
**

But every time I tried it, I ran into a message asking for output file path. So I filled it in with the command, '--output-folder', according to the Help menu.

So I tried to type in like this,

**
ffmpeg-normalize chapter1.mp3 -c:a libmp3lame -b:a 320k --output-folder /Users/Name/Audiobook/Destination -o chapter1_normalized.mp3

and then 'Output file path does not exist' message appeared, and it failed, and I wrote this one again with a tweak

ffmpeg-normalize chapter1.mp3 -c:a libmp3lame -b:a 320k -of /Users/Name/Audiobook/Destination -o chapter1_normalized.mp3
**

The same message showed up again and it didn't work again.

And then I searched for the solution to this issue online and in the FFmpeg-Normalize board. But I couldn't find the solution. And I'm not sure why this problem occurs although the directory (the output file path) really exists. When I read the manual, I thought that once I just wrote the input and output command, a folder called normalized would be automatically made up, and I'd get the normalized files. And I guess it is still true for other users. 

I'd like to appreciate any suggestion on this issue.

Thanks.

OS - Mac
FFMPEG Ver. - 4.2.2
FFMPEG-Normalize Ver. - 1.18.2

**Comment by slhck** [comment]
I see what the problem is. This was introduced by a recent bugfix. Will provide a fix shortly.

**Comment by slhck** [comment]
Please update to v1.19.0 and test again! Thanks!

**Comment by Yep101** [comment]
Thank you for the quick reply, slhck. I've now updated the app and tested it as you advised. It perfectly works! Many Thanks. :D 👍

ps. I have something to ask you. During the task, I always see the message, "Output folder normalized is ignored for input file --.mp3", and the program finally save normalized audio files in the same directory having original audio files. What does this message mean? I'm just curious about it. Thanks.
