### ISSUE TITLE
Loudnorm first and second pass way slower than manually with ffmpeg.

### ISSUE THREAD

**Issue by manus693** [slhck/ffmpeg-normalize#129]
ffmpeg -i *.avi" -af loudnorm=I=-23:LRA=7:tp=-2:print_format=json -f null -
This goes around 10 times faster or maybe more than first pass with ffmpeg-normalize.
Same happens with second pass.
Im using the same ffmpeg 64 bit from environment variables.

**Comment by slhck** [comment]
Please include all the information that was part of the bug report template so this can be reproduced. Thanks!
