### ISSUE TITLE
Improving progress bar

### ISSUE THREAD

**Issue by manus693** [slhck/ffmpeg-normalize#131]
**Is your feature request related to a problem? Please describe.**
It is a bit annoying that the progress bar leaves so many lines in CMD.

**Describe the solution you'd like**
I would like the progress bar to be like in ffmpeg.

**Describe alternatives you've considered**
Alternatively is of course to remove the -pr option, but I like to see the progress.

**Additional context**
![screenshot](https://user-images.githubusercontent.com/67372859/85573346-1846be00-b636-11ea-9e06-b5179db492d6.jpg)

**Comment by slhck** [comment]
Thanks for including the picture. But please, instead of deleting the template, fill it out completely. I need to know your OS and Python version. And which terminal you are using. And the compete debug output from the ffmpeg normalize command.

**Comment by manus693** [comment]
Maybe I have misunderstood, everything is working correctly, incredible work on the ffmpeg-normalize. Love it.
This was just a request if possible to change the progress bar to a one-liner.
Or isnt this how it shows for everyone else?

**Comment by slhck** [comment]
No, actually this is a bug, that's why I'm asking. It is supposed to stay on one line. If you can provide more info I can look into why that happens.

**Comment by manus693** [comment]
Python 3.8.3 64bit
Windows 1909 18363.900
ffmpeg version 4.3 64bit
Just installed the latest versions today of ffmpeg zeranoe and python.
Here is my bat-file

``setlocal EnableExtensions EnableDelayedExpansion
@ECHO OFF
chcp 65001
for %%a in ("*.avi") do if not exist "%%~na.wav" echo "%%~dpna.avi" && ffmpeg-normalize "%%~dpna.avi" -v -vn -pr -o "%%~dpna.wav"
pause``

**Comment by slhck** [comment]
Thanks for that extra info. Seeing that this is Windows, I believe the issue could be related to what is written here: https://pypi.org/project/tqdm/#faq-and-known-issues

> Windows: additionally may require the Python module colorama to ensure nested bars stay within their respective lines.

I’m not sure what that means for my code but I’ll investigate.

**Comment by manus693** [comment]
Yes, youre correct, installing colorama fixed it, thanks a lot!
Just ran `pip3 install colorama` in cmd.. :)

Probably everyone using windows without this knowledge has the same issue.
Probably many dont ever see it as a problem, as they might not add the `-pr` ?
Maybe somehow make it as a dependency? or inform about it in the readme?

Now it shows like this:
![screenshot](https://user-images.githubusercontent.com/67372859/85615148-10017980-b65c-11ea-8bce-91c37dffc5f0.jpg)

Everything is perfect now! GREAT!

**Comment by manus693** [comment]
And thank you so much! i just sent you a coffee! :)

**Comment by slhck** [comment]
Thank you, that is much appreciated! I will try to provide a fix by automatically including `colorama` (although I don't think I can do that for Windows users only … but it's a minor dependency anyway).

**Comment by manus693** [comment]
No problem, biggest thank it to you for your work with ffmpeg-normalize! :) 
But just adding it to the readme, "For Windows user: install colorama for python" And maybe add a link to this site [?](https://pypi.org/project/colorama/)  and maybe: `pip3 install colorama` or `pip install colorama`
And everything is ok, no? :)

**Comment by manus693** [comment]
And also one thing, this warning was the reason I added progress bar, "WARNING: Output folder normalized is ignored for input file" Was thinking there was something wrong.
This only appears when using `-o` as I understand, maybe remove it? Or change the text?

**Comment by slhck** [comment]
I fixed that too, thank you for bringing that to my attention!
