### ISSUE TITLE
Batch Reporting on Files

### ISSUE THREAD

**Issue by rpx91** [slhck/ffmpeg-normalize#133]
This seems exactly what I'm after! Thanks so much for maintaining and creating this.

I'd like to be able to report on the average volume level of mkv files i.e. RMS/dbfs. I don't want anything to be encoded but rather just a text file with the RMS/dbfs value written to a text file in the same directory as the mkv, and named the same as the mkv.

Is that possible at all?

The reason I'd like this is so that I can set my AVR to the correct reference volume for tracks without Dialnorm i.e. DTS or in remuxes that have stripped the Dolby DialNorm meta data

Thanks :) And I hope this is the right place to ask

**Comment by slhck** [comment]
Should be doable! But which operating system are you on?

You can use the `-n -p` option to show the statistics in JSON format. Those can be redirected to a file, one per input, via shell loops.

**Comment by rpx91** [comment]
Amazing!

I'm on Windows 10.

This will solve a big issue for a bunch of AVR users 😊


--
sent from my mobile

**Comment by rpx91** [comment]
I did a dry run and got the following output

```
 "input_i": "-25.00",
            "input_tp": "-3.47",
            "input_lra": "14.70",
            "input_thresh": "-36.03",
            "output_i": "-23.94",
            "output_tp": "-2.00",
            "output_lra": "8.40",
            "output_thresh": "-34.43",
            "normalization_type": "dynamic",
            "target_offset": "0.94"
```

Is the average volume the "input_thresh" number? I looked under help and the documentation but couldn't see anything.

**Comment by slhck** [comment]
The `input_i` field is the integrated loudness of the input. The `input_tp` is the true peak. Those are probably the two most important values. See: http://ffmpeg.org/ffmpeg-filters.html#loudnorm

Unfortunately I can't really help much with Windows batch scripts (i.e., looping, extracting the JSON, collecting the values), but I'm sure someone at https://superuser.com/ could help.

**Comment by rpx91** [comment]
OK thanks so much - your tool has been a massive help already anyway :)

I'll see if anyone on superuser can help out

**Comment by slhck** [comment]
You're welcome. Let me know if you need more info.

**Comment by rpx91** [comment]
One more quick question.

The integrated loudness, say it's -15. You have to minus that from the peak of the playback reference volume to get an average right? 

For example, I processed Spectre, the bond movie. It came out as -13.27. Godzilla came out at -15.29.  If I minus these values from 105db, the peak reference playback level of a movie I'll get average loudness right? So Bond is 91.73db.

At first that does seem very loud because movies are supposed to be 85db. But it's 85db per channel. So in a 7 channel movie I get why it's 92db. That would certainly need reducing just from a hearing safety point of view!

**Comment by slhck** [comment]
Hmm, I think you're much more informed than me on that particular subject :)
