### ISSUE TITLE
Can't extract just one audio track from video

### ISSUE THREAD

**Issue by PacoH** [slhck/ffmpeg-normalize#136]
I am trying to extract just one audio track and downmix it to mono from a video and can't get that to work. No matter what I try, all audio tracks get extracted. I have tried the following so far:

`ffmpeg-normalize "$f" -e="-filter_complex \"[0:1]loudnorm=I=-16:TP=-1.5:LRA=11:linear=true\" -ac 1" -vn -sn -cn -mn -c:a aac -b:a 160k -pr -p -o "$of"`
`ffmpeg-normalize "$f" -e="-map 0:1 -filter_complex \"loudnorm=I=-16:TP=-1.5:LRA=11:linear=true\" -ac 1" -vn -sn -cn -mn -c:a aac -b:a 160k -pr -p -o "$of"`

How can I do this?

**Comment by slhck** [comment]
I'm afraid this isn't possible, as the script makes use of the map option internally to correctly map the streams. I won't be able to reimpenent the whole ffmpeg mapping option syntax, so please manually extract the stream you wish to normalize first.

**Comment by slhck** [comment]
That sad I could warn the user if they tried to use map options as extra options for ffmpeg.

**Comment by PacoH** [comment]
OK, thanks. I just wrote a script to capture the output of the first pass and feed it into the second pass automatically. That way I can add any filters or options that I need.
