### ISSUE TITLE
Can't use codecs marked with experimental flag, such as 'dca'

### ISSUE THREAD

**Issue by M0shr00m** [slhck/ffmpeg-normalize#137]
Using any experimental audio codec for encoding, such as dca, requires the "-strict -2" or "-strict experimental" flag be placed in the ffmpeg call, specifically, right before the output specification, as shown [here](https://stackoverflow.com/questions/32931685/the-encoder-aac-is-experimental-but-experimental-codecs-are-not-enabled)

I have tried putting this flag in the '-e' and '-ei' sections, but ffmpeg-normalize responds with an "unrecognized argument" error.

Sample usage:
`ffmpeg-normalize "input.mkv" -e='-strict -2' -o "output.mkv" --audio-codec dca --audio-bitrate 1536k --target-level -21`

**Comment by slhck** [comment]
I cannot reproduce with the latest version. Please fill out the entire issue template so we can diagnose it, thanks!
