### ISSUE TITLE
Not an issue per say.

### ISSUE THREAD

**Issue by michaelcrossland1979** [slhck/ffmpeg-normalize#139]
Hi been a long time, I had stopped normalizing my files a while ago.
But here is what I would like cleared up for me.
Does your script handle MKV files that have 5.1 in AAC format? And what I mean by that is does it do the normalizing on all audio stream and output it as 5.1 or does it downmix it to 2.0 if you don't add exart stuff to tell it what to do?
If it the case of it being the latter one could you please help point out or let me know what I would need to do to get it to output 5.1 audio not downmix it.
Thank,
Michael

**Comment by slhck** [comment]
It should be possible to normalize 5.1 files with AAC encoding. Simply supply `-c:a aac` as the encoder. If you have problems getting it to work, please reopen, thanks!
