### ISSUE TITLE
Invalid Syntax 

### ISSUE THREAD

**Issue by TaoTeCha** [slhck/ffmpeg-normalize#143]
I'm not well versed in python but I'm pretty sure the hyphen in 'ffmpeg-normalize' is causing issues. I am running on google colab, which uses linux OS. I have tried cloning the git and a pip install, importing, changing directories. I keep getting invalid syntax and it points to just after the file name. A few times I have also gotten an error and it's hinting that it only recognizes only ffmpeg. I think I've read that python doesn't like hyphens in function and module names.

So what's going on and how can I fix it?
Thank you.

**Comment by slhck** [comment]
Please fill out the entire issue template. Thanks!

**Comment by TaoTeCha** [comment]
I don't know why it wasn't working that first night. I tried everything and nothing was working. The next day it worked on the first try. For people who want to use this in colab:

!pip install ffmpeg-normalize
!ffmpeg-normalize 'file.wav' (whatever your parameters are)

Thanks dude!

**Comment by slhck** [comment]
Okay, glad you got it solved.

If you have any further issues, please ask. Please make sure to fill out the issue template so it's easier to troubleshoot.
