### ISSUE TITLE
question for increased size after normalizing

### ISSUE THREAD

**Issue by okan35** [slhck/ffmpeg-normalize#151]
I made a normalization of a movie. First I removed audio tracks from movie with ffmpeg which left me with a size of 26 gb after this I normalized it and that produced a size of 43.8 gb of a movie. Is this normal ?

**Comment by slhck** [comment]
Yes, this is normal, as output will be uncompressed by default.

You can specify a different encoder, for example:

    ffmpeg-normalize *.mkv -c:a aac -b:a 192k

**Comment by okan35** [comment]
thanks, yeah I didn't use those parameters.

**Comment by okan35** [comment]
İ just used those parameters but it gave me a really shitty sound quality like terrible. Is it not possible to keep the same quality of sound but just have it normalized ?

**Comment by slhck** [comment]
As you observed, the only reliable and most compatible way to make it sound good is to do it in an uncompressed manner. That blows up the file size. 

You can use a higher bitrate (e.g. 320k) or any other encoder that ffmpeg supports. Is your input 5.1? Then you may need even higher rate.

**Comment by okan35** [comment]
It is basically DTS 7.1  remux of a 26 gm movie. Stream size in original file is 4.51 gb mp4a-A9 bit rate is 4958 kb/s format is DTD XLL X DTS HD

**Comment by slhck** [comment]
In this case, please choose an appropriate bitrate or VBR setting for the AAC encoder. If your ffmpeg supports it, using the libfdk_aac encoder will yield the highest AAC quality.

See the `--extra-output-options` option for examples of how to specify the VBR settings.

**Comment by okan35** [comment]
thanks, I will check that.
