### ISSUE TITLE
RFE: Add ability to do dynamic range compression or document how to do it.

### ISSUE THREAD

**Issue by JohnVillalovos** [slhck/ffmpeg-normalize#152]
Being able to normalize the volume is great. But sometimes even normalizing the audio has too much dynamic range which makes it necessary to adjust the volume which listening to the source material.

It would be very nice if there was an option to have it do dynamic range compression at the same time. Or document a way to do it. I could run dynamic range compression later, but I would prefer to limit the number of decode/encoding phases if possible.

Thank you!

**Comment by JohnVillalovos** [comment]
I'm unsure if `-lrt` in EBU accomplishes this or not.

**Comment by slhck** [comment]
There is no built-in way to perform dynamic adjustments, but you can use any of the filters present in ffmpeg to modify the signal before it gets normalized.

I added some examples on the wiki: https://github.com/slhck/ffmpeg-normalize/wiki/examples#filters

**Comment by JohnVillalovos** [comment]
Thanks for the info. As a note, I have noticed when using the `-lrt / --loudness-range-target` option that it appears to change the dynamic range. With value of 1.0 being the least amount of dynamic range and 20.0 would allow the most dynamic range.

I was doing tests and then comparing waveform graphs using the command:
```
$ ffmpeg -i test.mkv -filter_complex ""aformat=channel_layouts=mono,showwavespic=s=1000x400"" -frames:v 1 test.png
```

Also comparing numbers for example:
```
$ ffmpeg-normalize -p -n -f original.mkv
<snip>
        "ebu": {
            "input_i": "-16.49",
            "input_tp": "0.25",
            "input_lra": "21.60",
            "input_thresh": "-28.79",
            "output_i": "-23.57",
            "output_tp": "-2.00",
            "output_lra": "14.40",
            "output_thresh": "-34.50",
            "normalization_type": "dynamic",
            "target_offset": "0.57"
        },
<snip>
```
So in this file I can see that the Loudness Range (LRA) is 21.6 LU (`input_lra`), which is a pretty large dynamic range, in my opinion.

After running `ffmpeg-normalize` using the default settings it made a pretty good improvement. As `input_lra` went down to 14.5 LU. Also the graph visualization showed a dramatic difference to my eyes. The change in volume levels made it much more watchable.

Another way of generating the data is to use `ffmpeg` directly:
```
$  ffmpeg -i original.mkv  -af loudnorm=I=-16:dual_mono=true:TP=-1.5:LRA=11:print_format=summary -f null -
[Parsed_loudnorm_0 @ 0x55ae941ea700]
Input Integrated:    -16.5 LUFS
Input True Peak:      +0.2 dBTP
Input LRA:            21.6 LU
Input Threshold:     -28.8 LUFS

Output Integrated:   -16.5 LUFS
Output True Peak:     -1.5 dBTP
Output LRA:           16.5 LU
Output Threshold:    -27.7 LUFS

Normalization Type:   Dynamic
Target Offset:        +0.5 LU

$  ffmpeg -i test.mkv  -af loudnorm=I=-16:dual_mono=true:TP=-1.5:LRA=11:print_format=summary -f null -
[Parsed_loudnorm_0 @ 0x559128c4b040]
Input Integrated:    -23.0 LUFS
Input True Peak:      +0.3 dBTP
Input LRA:            14.5 LU
Input Threshold:     -33.9 LUFS

Output Integrated:   -16.3 LUFS
Output True Peak:     -1.5 dBTP
Output LRA:           11.1 LU
Output Threshold:    -27.0 LUFS

Normalization Type:   Dynamic
Target Offset:        +0.3 LU
```

**Comment by slhck** [comment]
Thanks for the insights! I haven't yet used that option much. Would you like to contribute an example in the wiki?

**Comment by JohnVillalovos** [comment]
> Thanks for the insights! I haven't yet used that option much. Would you like to contribute an example in the wiki?

I'll try to add some info. But the work-week has started...

**Comment by slhck** [comment]
No problem, I added a small example, but I also have to find some time to test the results.

**Comment by drmanhatin** [comment]
> Thanks for the info. As a note, I have noticed when using the `-lrt / --loudness-range-target` option that it appears to change the dynamic range. With value of 1.0 being the least amount of dynamic range and 20.0 would allow the most dynamic range.

Thanks for this John, will try this out on some Christopher Nolan movie 👍
