### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kalashnikovisme** [slhck/ffmpeg-normalize#154]
**Expected behavior**
FFmpeg should just run

**Actual behavior**

```shell
It crashes with any arguments
```

**Command**
```shell
 ffmpeg-normalize
```

```
Traceback (most recent call last):
  File "/home/tramway/.local/bin/ffmpeg-normalize", line 7, in <module>
    from ffmpeg_normalize.__main__ import main
  File "/home/tramway/.local/lib/python2.7/site-packages/ffmpeg_normalize/__init__.py", line 1, in <module>
    from ._ffmpeg_normalize import FFmpegNormalize
  File "/home/tramway/.local/lib/python2.7/site-packages/ffmpeg_normalize/_ffmpeg_normalize.py", line 26
    f"{name} must be within [{min_r},{max_r}]"
                                             ^
SyntaxError: invalid syntax

```

**Environment (please complete the following information):**
- [x] Your operating system. Ubuntu 16.04
- [x] Your Python version / distribution (`python --version`). Python 3.7.10.
- [x] Your ffmpeg version (`ffmpeg -version`). ffmpeg version 4.3.2-0york0~16.04 Copyright (c) 2000-2021 the FFmpeg developers

**Comment by slhck** [comment]
My guess is that the pip you were using to install ffmpeg-normalize was from the Python 2.7 installation. Please make sure you are using Python 3 pip.

Closing for now as this is not an ffmpeg-normalize issue but a system configuration problem.

**Comment by kalashnikovisme** [comment]
Yes, it was system configuration issue. Solved with `pyenv global` command. Thanks!
