### ISSUE TITLE
Consider adding to conda-forge

### ISSUE THREAD

**Issue by ning-y** [slhck/ffmpeg-normalize#158]
**Is your feature request related to a problem? Please describe.**
I think conda is an active and growing package manager. It would be nice to be able to install ffmpeg-normalize via conda.

**Describe the solution you'd like**
ffmpeg-normalize is added to the conda-forge channel of the anaconda repository.

**Describe alternatives you've considered**
pip3 is obviously an alternative, in fact, the recommended install method. Having this on conda is just nice for projects which are already wholly managed by conda.

**Comment by slhck** [comment]
Thanks, this is a good suggestion. I haven't used conda yet so it didn't occur to me that it needed a separate repository.

I'll put this in my agenda.

**Comment by slhck** [comment]
I've done some quick research, and it seems that one has to create some extra metadata that references the project here, which has to be maintained in addition.

I would like to understand why having the package on conda would be an added benefit that outweighs the extra maintenance burden on me.

Wouldn't it suffice to do:

```
conda install pip
pip install ffmpeg-normalize
```

within an Anaconda environment?

**Comment by slhck** [comment]
So it seems I have to not only release this package in conda-forge, but also my own dependent packages (`ffmpeg-progress-yield`): https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=408510&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1056

This is too much effort for me at the moment. If it's not a huge burden I would recommend simply using `pip` to install the package for the time being.

**Comment by ning-y** [comment]
Thank you so much for taking the time to look through this request! You're right about `pip`, I think. The conda stuff is just nice to have in terms of deployment. Hopefully someone coming across this issue will help (I am a bit swamped at the moment too)

**Comment by slhck** [comment]
FWIW I have two open PRs here

- https://github.com/conda-forge/staged-recipes/pull/17036
- https://github.com/conda-forge/staged-recipes/pull/16890

**Comment by slhck** [comment]
These have been merged, so it should be available now or soon.

**Comment by ning-y** [comment]
Thank you very much!
