### ISSUE TITLE
"argument list too long" when there are too many files

### ISSUE THREAD

**Issue by ziadloo** [slhck/ffmpeg-normalize#162]
**Expected behavior**
I tried to normalize 297,984 files (mp3s) in a folder

**Actual behavior**
The program errored out with the following error message:
```
argument list too long: ffmpeg-normalize
```

**Command**

```
ffmpeg-normalize ./clips/*.mp3 -of ./norm -ext mp3 -c:a mp3
```

Any output you get when running the command with the `--debug` flag:

The same as without `--debug`
```
argument list too long: ffmpeg-normalize
```

**Environment:**
- [ ] OS: `Linux *** 5.15.12-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:08:07 UTC 2021 x86_64 GNU/Linux`
- [ ] Your Python version / distribution (`python --version`): `Python 3.8.12`
- [ ] Your ffmpeg version (`ffmpeg -version`):
```
ffmpeg version n4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11.1.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```

**More info**

* This is rather up-to-date hardware with 64GB of RAM and Core-i9. I hardly doubt that the code ran out of resources.
* Trying one file at a time seems to work.
* The program errors out in a matter of seconds (2~3 seconds)

**Comment by slhck** [comment]
This is rather an error with the shell. The glob expands to a list that's simply too long.

Try running ls with the same glob and it will break as well.

I would recommend using GNU Parallel for such large tasks. It's faster (since it'll use all your cores) and you can pipe the list of files to it: https://stackoverflow.com/a/23121083/435093

**Comment by ziadloo** [comment]
Thanks, @slhck for the tip. You are absolutely right. A simple `ls *.mp3` fails as well.

For anyone else who might be struggling with the same problem, this worked for me like a charm:

```
find -type f -name '*.mp3'  | parallel "ffmpeg-normalize {} -of ./norm -ext mp3 -c:a mp3"
```
