### ISSUE TITLE
Is it possible to assign the output to a python variable instead to an output file? Something similar to "pipe:1" option in FFmpeg.

### ISSUE THREAD

**Issue by Msenous15** [slhck/ffmpeg-normalize#165]
Is it possible to assign the output to a python variable instead to an output file? Something similar to "pipe:1" option in FFmpeg.

**Comment by slhck** [comment]
If I understand you correctly, no, this is not possible. This tool assumes writing to an output file in a temporary location, then renaming that file to its final location. Can you explain your use case in more detail?

**Comment by Msenous15** [comment]
Thank you so much for your speedy reply.
In this [example](https://superkogito.github.io/blog/ffmpegpipe.html), we can see how we can assign to output of ffmpeg to a python variable so we can use is directly in our scripts without the need of writing it to a file then read it again.   
Thanks again

**Comment by slhck** [comment]
I see. I think that would require a bit of restructuring, since I assume a file being written. Also, the command running utility class was made for outputting progress through the stdout pipe. I am not sure I can easily replace that. What type of normalization do you intend to use? It might be easier to directly call the ffmpeg command yourself and maybe just borrow some code from this tool related to parsing loudness statistics.

**Comment by Msenous15** [comment]
I'm normalizing the volume using a RMS-norm (-nt rms -t=-27).
I appreciate your help,  I will try to figure out a way to perform it, otherwise your tool is super helpful, I can keep use it as is it.
Thank you a lot.

**Comment by Msenous15** [comment]
I am sorry, I forget to mention that I need also to downsample to 16Khz after volume normalization!
"ffmpeg-normalize " + In_file + " -nt rms -t=-27 -o " + out_file + " -ar 16000 -f"

**Comment by slhck** [comment]
In that case I would recommend you writing a program similar to the example you've linked to, with one additional first pass that doesn't use pipes. Here's some dummy code to get you started (unchecked, but you get the idea).

```python
import re
import subprocess

input_file = "..."
normalization_type = "rms" # or peak
target_level = -23

cmd = ["ffmpeg", "-nostdin", "-y", "-i", input_file, "-af", "astats=measure_overall=Peak_level+RMS_level:measure_perchannel=0", "-vn", "-sn", "-f", "null", "/dev/null"]

output = subprocess.check_output(cmd, stderr=subprocess.STDOUT, universal_newlines=True)

mean_volume_matches = re.findall(r"RMS level dB: ([\-\d\.]+)", output)
if mean_volume_matches:
    detected_mean = float(mean_volume_matches[0])
else:
    raise RuntimeError("Could not detect mean volume")

max_volume_matches = re.findall(r"Peak level dB: ([\-\d\.]+)", output)
if max_volume_matches:
    detected_max = float(max_volume_matches[0])
else:
    raise RuntimeError("Could not detect max volume")

if normalization_type == "peak":
    adjustment = 0 + target_level - detected_max
elif normalization_type == "rms":
    adjustment = target_level - detected_mean

cmd = ["ffmpeg", "-nostdin", "-y", "-i", input_file, "-af", f"volume={adjustment}dB", "-vn", "-sn", "-f", "wav", "pipe:1"]

# TODO run command and get directly in memory
```

Hope that helps.

At the moment I do not plan adding support for pipes. If anyone has a good idea on how to integrate this while keeping the possibility for showing progress, PRs are welcome!

**Comment by Msenous15** [comment]
Thank you so much @slhck, this should be definitely helpful.
