### ISSUE TITLE
[Question] Can the output from `--print-stats` be used to determine if an audio track is silent?

### ISSUE THREAD

**Issue by thenewguy** [slhck/ffmpeg-normalize#167]
I am trying to detect audio tracks that contain silence and remove them from output encoding.  Dilemma - I am not sure how to accurately determine if a track is silent.

Can the output from `--print-stats` tell us if an audio track produces any kind of noise or if it is completely silent?  Any tips on how I could accomplish this?

**Comment by slhck** [comment]
ffmpeg has its own silencedetect filter, which would be the most suitable here. You do have to set a threshold in dB in terms if what you consider silence.

**Comment by slhck** [comment]
Actually, you can use the `astats` filter for this, e.g.:

```
➜ ffmpeg -f lavfi -i anullsrc -af astats -t 1 -f null /dev/null 2>&1 | grep -E 'Channel|Peak'
[Parsed_astats_0 @ 0x14ae08b00] Channel: 1
[Parsed_astats_0 @ 0x14ae08b00] Peak level dB: -inf
[Parsed_astats_0 @ 0x14ae08b00] Peak count: 92160
[Parsed_astats_0 @ 0x14ae08b00] Channel: 2
[Parsed_astats_0 @ 0x14ae08b00] Peak level dB: -inf
[Parsed_astats_0 @ 0x14ae08b00] Peak count: 92160
[Parsed_astats_0 @ 0x14ae08b00] Peak level dB: -inf
[Parsed_astats_0 @ 0x14ae08b00] Peak count: 92160.000000
```

The `volumedetect` filter would incorrectly report the input as -91 dB here.

I just pushed a small bugfix. Now this tool can also print the infinity values:

```
➜ ffmpeg-normalize null.wav -f -n -nt peak -p
[
    {
        "input_file": "null.wav",
        "output_file": "normalized/null.mkv",
        "stream_id": 0,
        "ebu": null,
        "mean": -Infinity,
        "max": -Infinity
    }
]
```

**Comment by thenewguy** [comment]
Does this mean the `ffmpeg-normalize` script can be used for this now? Does "-Infinity" for "max" mean silence here?

**Comment by slhck** [comment]
Yes, "infinity" would mean absolute silence. If there was any noise whatsoever, you would get a low dB score.
