### ISSUE TITLE
ERROR: No file exists at \ffmpeg\bin

### ISSUE THREAD

**Issue by macgile** [slhck/ffmpeg-normalize#169]
**:warning: Please read this carefully! If you do not fill out this information, your bug report may be closed.**

**Expected behavior**
Normalize video file

**Actual behavior**
The program returns the following error:
ERROR: No file exists at C:\Users\GILLES\Downloads\Portable\ffmpeg\bin

It seems to point to the ffmepg installation folder
I specify that all the paths of the environment variables are correct:

**Command**
The exact command you were trying to run:

```
C:\>ffmpeg-normalize --debug C:\\Users\\GILLES\\Downloads\\1648334270.mp4 -o C:\\Users\\GILLES\\Downloads\\output.mp4 -c:a aac -b:a 192k
```

Any output you get when running the command with the `--debug` flag:

```
C:\>ffmpeg-normalize --debug C:\\Users\\GILLES\\Downloads\\1648334270.mp4 -o C:\\Users\\GILLES\\Downloads\\output.mp4 -c:a aac -b:a 192k

ERROR: FFmpegNormalizeError: No file exists at C:\Users\GILLES\Downloads\Portable\ffmpeg\bin
Traceback (most recent call last):
  File "C:\Users\GILLES\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\GILLES\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\GILLES\AppData\Local\Programs\Python\Python310\Scripts\ffmpeg-normalize.exe\__main__.py", line 7, in <module>
  File "C:\Users\GILLES\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg_normalize\__main__.py", line 468, in main
    ffmpeg_normalize = FFmpegNormalize(
  File "C:\Users\GILLES\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg_normalize\_ffmpeg_normalize.py", line 67, in __init__
    self.ffmpeg_exe = get_ffmpeg_exe()
  File "C:\Users\GILLES\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg_normalize\_cmd_utils.py", line 138, in get_ffmpeg_exe
    raise FFmpegNormalizeError(f"No file exists at {ffmpeg_exe}")
ffmpeg_normalize._errors.FFmpegNormalizeError: No file exists at C:\Users\GILLES\Downloads\Portable\ffmpeg\bin
```

**Environment (please complete the following information):**
- [windows 10] Your operating system
- [Python 3.10.1] Your Python version / distribution (`python --version`)
- [ ffmpeg version 4.4.1-full] Your ffmpeg version (`ffmpeg -version`)

**Comment by slhck** [comment]
Do you have the environment variable `FFMPEG_PATH` set? The error can only appear when this particular env variable is set. If set, it must point directly to an ffmpeg binary:

https://github.com/slhck/ffmpeg-normalize/blob/db624b329a325d938053d4ec7e9596e5a3e83843/ffmpeg_normalize/_cmd_utils.py#L133-L138

Please unset the environment variable, or point it to `ffmpeg` directly.

**Comment by macgile** [comment]
Hi,
 Yes it is defined like this:  

![Capture](https://user-images.githubusercontent.com/577257/159231912-3aad5969-f462-48ab-ac87-de442de2b4c6.PNG)

**Comment by macgile** [comment]
The name of the ffmpeg executable in the bin folder is not **ffmpeg_exe** but **ffmpeg.exe**

![Capture](https://user-images.githubusercontent.com/577257/159232592-c30c97c7-3c10-493c-a960-729db13f919d.PNG)

**Comment by slhck** [comment]
As I mentioned above, please unset the environment variable, or point it to `ffmpeg.exe` directly.

**Comment by macgile** [comment]
with the name of the executable in the environment variable it works 

Thank's for your great work !
Best regards

**Comment by slhck** [comment]
Glad you got it working now!
