### ISSUE TITLE
HEVC compatibility

### ISSUE THREAD

**Issue by lgarron** [slhck/ffmpeg-normalize#172]
I'd love to try this out, but unfortunately it doesn't seem to work on HEVC (H.265) 😢

```
[ipod @ 0x12bf04670] Could not find tag for codec hevc in stream #0, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 --
[Parsed_loudnorm_0 @ 0x12bf0a4f0]
```

My `ffmpeg` install is compiled with HEVC support, so I presume that's not the issue.

**Comment by slhck** [comment]
Please fill out the entire issue template.

**Comment by lgarron** [comment]
I'm afraid I don't know anything except I got an error on the very first file I tried, just wanted to report it.

I'll probably be looking for alternatives, I can file a more detailed and any debug info if I come back to this project.

**Comment by slhck** [comment]
Please create a new issue and look at the text that is in the description. There you will find steps to include debug information.

I'm sure your problem can be sorted out, you just need to provide more information. Thanks.

**Comment by lgarron** [comment]
> Please create a new issue and look at the text that is in the description. There you will find steps to include debug information.

Ah, I think I understand, you're referring to the bug report template?
(I had clicked on the "feature request" template, which does not include such steps.)

**Comment by slhck** [comment]
Yes. I now realize you must have thought this was a lack of a feature. Of course HEVC decoding is supported. Please just open a new issue with all the info included, and we'll sort it out.
