### ISSUE TITLE
Spaces problem

### ISSUE THREAD

**Issue by dave-low** [slhck/ffmpeg-normalize#18]
Running on linux, if I pass a filename in with multiple consecutive spaces, ffmpeg gets a filename with the block if spaces converted to a single space and it then cannot find the file.
e.g. 'test   name' gets passed to ffmpeg as 'test file'

**Comment by slhck** [comment]
Should be working now if you do a pip upgrade of the package.

**Comment by dave-low** [comment]
Hi, that works fine now.
Many thanks for prompt response and a useful program.

Dave Low
 
Home: 01394 671176
Mobile: 07736 636859
