### ISSUE TITLE
Tool chain with sickbeard_mp4_automator

### ISSUE THREAD

**Issue by sdfg2** [slhck/ffmpeg-normalize#185]
Along with getting this working for my lidarr setup, I've been working on using https://github.com/mdhiggins/sickbeard_mp4_automator for my sonarr/radarr setup, and I've got a question for you if you don't mind about the best way of integrating `ffmpeg-normalize` with `sma`.

`sma` lets me apply `ffmpeg` filters to any of the audio streams it deals with, which I guess could include `loudnorm` which I believe is what is used in `normalize`.  But I think `normalize` does _two_ passes to get a more accurate result.

Combined with the fact that most media these days has more than 2 channels, and I'm only interested in _having_ two channels, I'm not sure what the best tool chain is in this case.  Should I just let `sma` do its magic and downsample the channels and then clear up the streams and _then_ pass the file over to `normalize`?  (I just tried that actually, it took twice as long, kinda obviously!)

There's something in my brain going 'both of these tools are doing multiple passes, surely there's a way to combine them in such a way that as few passes as possible are made'.

**Comment by slhck** [comment]
I think the best way to go in your case would be to downmix first and work with the 2.0 file. I am not sure how loudnorm deals with multichannel audio, and whether that's even supported properly.

This is, obviously, going to take twice as long, unless the `sickbeard_mp4_automator` program incorporates similar functionality as ffmpeg-normalize, in the sense of parsing the first pass values and applying them during the second pass. That seems like the only reasonable solution here.

**Comment by sdfg2** [comment]
Yeah, the filter lines are already quite complicated, don't think it would be good to mess with them:

```
[Audio.ChannelFilters]
6-2 = pan=stereo|FL < 1.0*FL + 0.707*FC + 0.707*BL|FR < 1.0*FR + 0.707*FC + 0.707*BR
7-2 = pan=stereo|FL < 0.321953*FC+0.455310*FL+0.394310*SL+0.227655*SR+0.278819*BC+0.321953*LFE|FR < 0.321953*FC+0.455310*FR+0.394310*SR+0.227655*SL+0.278819*BC+0.321953*LFE
8-2 = pan=stereo|FL < 0.274804*FC+0.388631*FL+0.336565*SL+0.194316*SR+0.336565*BL+0.194316*BR+0.274804*LFE|FR < 0.274804*FC+0.388631*FR+0.336565*SR+0.194316*SL+0.336565*BR+0.194316*BL+0.274804*LFE
```

It probably is best just to apply it afterward.  Not like I can't just run a batch over night or something, I don't have to stare at the progress bar!
