### ISSUE TITLE
Add an option to see the ffmpeg command being called

### ISSUE THREAD

**Issue by sdfg2** [slhck/ffmpeg-normalize#186]
**:warning: Please read this carefully and edit the example responses! If you do not fill out this information, your feature request may be closed without comment.**

**Is your feature request related to a problem? Please describe.**
I'm not sure whether the `-e` options I'm sending to `ffmpeg` are getting eaten by `ffmpeg-normalize` or `ffmpeg` itself.

**Describe the solution you'd like**
Add the whole command being sent to `ffmpeg`, either via the `-v` switch or a new one.

**Comment by slhck** [comment]
Pass the `-d` option to see a detailed debug log.

**Comment by sdfg2** [comment]
Oops!
