### ISSUE TITLE
Normlization of multi-audio-tracks files

### ISSUE THREAD

**Issue by cgrima** [slhck/ffmpeg-normalize#19]
Hi,

Currently, when ffmpeg-normalize processes a video file with several audio tracks (for example with different language), the code does consider only one track so that the output misses the other audio tracks.

Would it be possible for ffmpeg-normalize to apply the desired normalization to all the audio tracks within a video file?

Thanks

**Comment by slhck** [comment]
That's a good suggestion. However, it's a little bit more complicated to implement. I'm guessing the first option would be implementing a switch to select the audio track ID to be normalized.

I'll have a look if I find the time!

**Comment by Jiab77** [comment]
Hi, 

I think this could be done by using `ffprobe` to list all audio tracks ?

**Comment by slhck** [comment]
@Jiab77 Thanks for the suggestion. That's correct – I know *how* to get it done, it just needs to be implemented at some point.

**Comment by Jiab77** [comment]
@slhck I did some `ffprobe` parsing by using the `csv` output format but it is in `batchscript`, not in `shellscript`. Later I've planned to port this code into `php`

**Comment by Jiab77** [comment]
@slhck for the `ffprobe` parsing code, please see https://github.com/Jiab77/BJRencoder/blob/master/ffscan.bat

**Comment by slhck** [comment]
Yes, thanks – as I said, the parsing itself is not the problem! I just need to find a lazy Sunday afternoon with bad weather to get started.

By the way, unless you're doing something super-customized, you may find https://github.com/PHP-FFMpeg/PHP-FFMpeg useful.

**Comment by Jiab77** [comment]
Yes I understand. About your suggestion, I've read already about this project but unfortunately, my project would be too much complex to use their existing codebase. I've done something in my last job and you've helped me a lot by your posts on stackoverflow, those related to  `ffmpeg`.

So thanks a lot for your help :+1:

**Comment by slhck** [comment]
A year later, but this is now possible with version 1.0.

**Comment by Jiab77** [comment]
Wow thx alot ! @slhck
