### ISSUE TITLE
Switch to ignore the AUDIO_ONLY_FORMATS

### ISSUE THREAD

**Issue by shnurks** [slhck/ffmpeg-normalize#191]
**Is your feature request related to a problem? Please describe.**
I'm trying to normalize a bunch of ogg vorbis files which have (non-standard?) cover art as an `mjpeg` stream. When just running the command I get from the `-d` option with `-c:v mjpeg` it works flawlessly.

**Describe the solution you'd like**
It would be great to have a switch such as `--force-video` to prevent it from dropping the cover.

**Describe alternatives you've considered**
Running ffmpeg-normalize with `--run-dry -d` with a .mkv as the target and then parsing the result, adding `-c:v mjpeg` and changing the target file to an .ogg works but is somewhat inelegant. (And might be difficult for beginners to ffmpeg.)

**Comment by slhck** [comment]
Hmm, maybe we don't even have to drop the cover by default.

Does `-c:v copy` work as well with the `.ogg` output? Can you please show the original command you've tried?

**Comment by shnurks** [comment]
Okay, so I double checked and it turns out I forgot to actually change the target file to an .ogg. So I guess it's an issue of ffmpeg and ffmpeg-normalize works as intended. Sorry for that.

```[ogg @ 000001105eb51880] Frame rate very high for a muxer not efficiently supporting it.
Please consider specifying a lower framerate, a different muxer or -vsync 2
[ogg @ 000001105eb51880] Unsupported codec id in stream 0
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 --```
