### ISSUE TITLE
Can default ffmpeg loudnorm be used for speech?

### ISSUE THREAD

**Issue by kb-open** [slhck/ffmpeg-normalize#219]
`ffmpeg` (version 4.3) does not seem to have `speechnorm` anymore (even though their documentation mentions availability of `speechnorm`). Therefore, can the default `ffmpeg loudnorm` be used for speech? Or, would you recommend using `ffmpeg-normalize`?

**Comment by slhck** [comment]
ffmpeg 4.3 is outdated. Please update to the most recent version. You can find static builds for it on ffmpeg.org.
