### ISSUE TITLE
Allow overwriting the input file

### ISSUE THREAD

**Issue by reuben** [slhck/ffmpeg-normalize#22]
Is there any reason why overwriting the input file with the output file is currently forbidden?

**Comment by slhck** [comment]
It's not impossible, but when you do it with ffmpeg, it will truncate and damage the input file.

This could be achieved by creating a temporary file and then renaming it, but it's something I did not foresee since it can be easily done with a shell loop.

But it's on my TODO list!

**Comment by slhck** [comment]
This should be possible now with `-uxf`.

**Comment by reuben** [comment]
Awesome, thanks! :)
