### ISSUE TITLE
Please consider using `static-ffmpeg` to eliminate `ffmpeg` explicit dependency

### ISSUE THREAD

**Issue by zackees** [slhck/ffmpeg-normalize#220]
https://github.com/zackees/static-ffmpeg
`pip install static-ffmpeg`

```python
import static_ffmpeg
static_ffmpeg.add_paths(weak=True)  # only installs if ffmpeg is not currently in path
```

This will eliminate an installation step and make the system work out of the box. `static-ffmpeg` works for Mac/Windows/Ubuntu

**Comment by slhck** [comment]
Thanks for the suggestion.

While I understand the purpose of your package, and I agree that “working out of the box” would be a nice feature, I am not comfortable with adding this kind of third-party dependency.

Some reasons and constructive feedback:

- It performs unverified binary installs. I wouldn't trust a random GitHub repo for binary downloads without checksum validation … perhaps you want to add such a feature in the future.
- It writes to a somewhat arbitrary location that will be hard to find later on; I'd rather users know where they installed ffmpeg and can update that using the recommended methods and “official” static builds.
- The binaries you provide are already outdated.
- Your binary distribution violates the FFmpeg license, as you don't give proper credit.

**Comment by slhck** [comment]
I updated the README to point users to places and methods to install ffmpeg.
