### ISSUE TITLE
Extreme filesize increase

### ISSUE THREAD

**Issue by Lightningblade** [slhck/ffmpeg-normalize#224]
I used ffmpeg-normalize to normalize a movie, which originally was 1,38 GB. The normalized version is 14,2 GB.
Why does it re-encode the video instead of just replacing the audio track?

**Comment by slhck** [comment]
The video is not being reencoded. The audio is output as PCM uncompressed by default.

Please refer to the README, and choose an audio encoder that you want to use for the output.

Next time posting, please do not delete the issue template.

**Comment by Lightningblade** [comment]
Sorry, it didn't occur to me that audio could ever fill that much.

I just commented again to say, there is no issue template when choosing question/support.

**Comment by slhck** [comment]
Thanks for letting me know, I will fix this!
