### ISSUE TITLE
keep-loudness-range-target throws unrecognized argument

### ISSUE THREAD

**Issue by snblackout** [slhck/ffmpeg-normalize#226]
**Describe what you are attempting to do**

Documentation on main page shows `--keep-loudness-range-target` as an option but errors when you try to use it.

Printing usage doesn't list this.  Is this option removed?

**Comment by snblackout** [comment]
After more investigating, it's not happening on Windows after using pip3 install, but on my Ubuntu laptop using pip3 install it errors with that argument unrecognized.  

Is the latest release not fully available through the Linux channels?  Curious.

Ubuntu version: `ffmpeg-normalize v1.23.1`
Windows version: `ffmpeg-normalize v1.26.6`

Looks like it.

**Comment by slhck** [comment]
Please check your Python version. Yours might be outdated. Use at least Python 3.8.

**Comment by slhck** [comment]
Cloding due to lack of feedback/details, please comment if you are using a recent Python version and still observe the problem.
