### ISSUE TITLE
Normalized FLAC file is 24-bit (original is 16-bit)

### ISSUE THREAD

**Issue by stavroblofeld** [slhck/ffmpeg-normalize#23]
Is there a setting to have the normalized file match the same bit rate as the original file?

**Comment by slhck** [comment]
It's not possible to do it directly. This would require parsing the input and then selecting the matching output sample rate. It's on my TODO list though.

What you can do if you know that your input is 24-bit: Use the `--acodec pcm_s24le` option to specify a different sample rate for the output WAV file.

**Comment by stavroblofeld** [comment]
Thanks for the quick response.  This will be a great feature.


In the meantime, I'll try what you suggest.

________________________________

**Comment by slhck** [comment]
This is now possible with version 1.0 — it'll try to estimate the bit depth from the input file and use the same for output. However, this only works for PCM WAV at the moment.
