### ISSUE TITLE
Specify output folder and create one if doesn't exist

### ISSUE THREAD

**Issue by iamdannywyatt** [slhck/ffmpeg-normalize#248]
Is it possible to convert the MP3 directly to a folder if it exists and if not, create the folder and convert into it directly?

This is my script (I'm using Keyboard Maestro, hence the $KMVAR_Local__basename
`ffmpeg-normalize "$KMVAR_Local__basename.mp3" -f -c:a libmp3lame -b:a 320k -nt peak -t -1 --output "$KMVAR_Local__basename - normalized.mp3"`

So I would like the file to be converted to a folder "Normalized -1" that should already be in the same folder as the source file and if it doesn't, it creates it and then converts it to it.

Is this possible?

**Comment by slhck** [comment]
I would recommend you add a line before, in your script, that creates the directory:

    mkdir -p /path/to/directory

This should be possible within Keyboard Maestro directly!

**Comment by iamdannywyatt** [comment]
@slhck thanks.
I was using KM's action to create the folder. My issue was that I wasn't using the right script to convert the audio directly to that folder. I have fixed it now.
Appreciate it!
