### ISSUE TITLE
Add possible to select stream to normalize

### ISSUE THREAD

**Issue by Mattarn** [slhck/ffmpeg-normalize#249]
The readme states :

>  What will get normalized?
> 
>  By default, all streams from the input file will be written to the output file. For example, if your input is a video with two language tracks and a subtitle track, both audio tracks will be normalized independently. The video and subtitle tracks will be copied over to the output file

Please add possibility to normalize only selected streams.
For example, my file have 8 track, i want only normalize TR1 and TR2 together

**Comment by slhck** [comment]
Please see: https://github.com/slhck/ffmpeg-normalize/issues/104

This would mean re-implemeting the map option from ffmpeg, and consequently changing the logic for counting tracks etc. PRs for this functionality are welcome, but I don't have time to work on it at the moment.

**Comment by bitozoid** [comment]
If I want just one audio stream from the input, I usually add to `ffmpeg` something like `-map 0:a:3` where 3 is the fourth audio channel.

From https://trac.ffmpeg.org/wiki/Map:

> -map 1:a:2 refers to "second input:audio only:third audio stream".

I wonder whether generating a file with just one output stream would be easy to implement. I mean, to add an option to select the audio stream from the input file and only output that stream.

**Comment by slhck** [comment]
For the reasons mentioned above, this is currently not possible without a major overhaul of the map logic. Better to first extract the stream you want with ffmpeg itself, and then normalize that on its own.
