### ISSUE TITLE
Allow force-overwrite when normalizing

### ISSUE THREAD

**Issue by bitops** [slhck/ffmpeg-normalize#25]
I was doing a bulk conversion of audio files when I noticed some files hadn't been converted. I ran the tool with verbose output and noticed this output:

```shell
2017-04-17 01:58:59,787 - ffmpeg_normalize - INFO - file needs -0.1 dB gain to reach -26 dB
2017-04-17 01:58:59,787 - ffmpeg_normalize - INFO - gain = -0.1, will not adjust file
```

I appreciate that no unnecessary work will be done here, but for bulk scripting it's sometimes useful to make a copy even if no processing needed to happen. Anyway, not a big deal, but could be a nice feature. Thanks!

**Comment by slhck** [comment]
I agree it'd be useful to prevent this. However, there is a threshold setting that you can change for that purpose. Just specify:

    --threshold 0
