### ISSUE TITLE
Combining ffmpeg-normalize with ffmpeg pan filer

### ISSUE THREAD

**Issue by Corruptsmurf** [slhck/ffmpeg-normalize#253]
I am trying to merge ffmpeg-normalize and my typical surround-to-stereo downmixing script.

My normal script in ffmpeg would look like: 
`ffmpeg -i UTS.mkv -map 0:a:0? -c:a:0 aac_at -aac_at_mode 3 -global_quality:a 14 -filter:a:0 "pan=stereo|FL=1.414*FC+0.707*FL+0.5*FLC+0.5*BL+0.5*SL+0.5*LFE|FR=1.414*FC+0.707*FR+0.5*FRC+0.5*BR+0.5*SR+0.5*LFE,acompressor=ratio=4" -o UTS_aac.mkv`

These options take a custom pan of the surround sound channels to generate a dialogue-heavy stereo mix that preserves the LFE channel, then applies the acompressor filter.  I thought it would be nice to run normalization on top of that (or at least test it out).  

I tried the following syntax: 
`ffmpeg-normalize UTS.mxv --keep-loudness-range-target -c:a aac -e="-aac_at_mode 3 -global_quality:a 14 -filter:a:0 "pan=stereo|FL=1.414*FC+0.707*FL+0.5*FLC+0.5*BL+0.5*SL+0.5*LFE|FR=1.414*FC+0.707*FR+0.5*FRC+0.5*BR+0.5*SR+0.5*LFE,acompressor=ratio=4"" -o UTS_normal.mkv`  

That resulted in this error:  
`'FL' is not recognized as an internal or external command, operable program or batch file.`  
  
  
I also tried:  
`ffmpeg-normalize UTS.mkv --keep-loudness-range-target -c:a aac -e '[ "-aac_at_mode", "3", "-global_quality:a", "14", "-filter:a:0", "pan=stereo|FL=1.414*FC+0.707*FL+0.5*FLC+0.5*BL+0.5*SL+0.5*LFE|FR=1.414*FC+0.707*FR+0.5*FRC+0.5*BR+0.5*SR+0.5*LFE,acompressor=ratio=4" ]' -o UTSnormal.mkv`  
   
Which resulted in a different error:  
`ffmpeg-normalize: error: argument -f/--force: ignored explicit argument 'ilter:a:0,'`  
   
My apologies if this is a dumb question; I just can't seem to figure out this syntax and would really appreciate some help.  

Thanks.

**Comment by Corruptsmurf** [comment]
I also changed the ' ' marks to " " in the second syntax example and ran it again. That resulted in the first error again ('FL' is not recognized...)

**Comment by slhck** [comment]
Not on a computer right now, so I can only guess, but you're going to want to use the "pre filter" or "post filter" options instead of the "extra" option. You cannot override the entire filter chain, since that is what ffmpeg-normalize will be using for its internal processing.

Regarding the pipe symbol, you may have to escape that with a backslash, since otherwise it may be interpreted as piping the output to another command.

**Comment by slhck** [comment]
See here for some examples of pre filtering: https://github.com/slhck/ffmpeg-normalize/wiki/examples#filters

**Comment by SerSout** [comment]
How am i supposed to apply "-ac 2" for a stereo downmix? cause "pre filter" option doesn't work

**Comment by slhck** [comment]
For that, use the `--extra-output-options` option. The audio channel option in ffmpeg is not a filter, so it needs to be applied to the output file and cannot be used in the pre-filter list of filters.

**Comment by SerSout** [comment]
So, running a pass of ffmpeg with the "-ac 2" option then run ffmpeg normalize it's not the same as running a single pass of ffmpeg-normalize with -ac 2 option?

**Comment by slhck** [comment]
That should be the same. You can downmix in ffmpeg-normalize, too.

**Comment by SerSout** [comment]
Yes but the output is downmixed, so the normalization is applied to each channel then downmixed, i doubt that those opreations are linear

**Comment by SerSout** [comment]
It's different, cause ffmpeg's "-ac 2" lower the volume of the ouput file, here it's what i found googling around https://superuser.com/questions/852400/properly-downmix-5-1-to-stereo-using-ffmpeg

**Comment by slhck** [comment]
I would recommend to downmix first just using ffmpeg, then use ffmpeg-normalize to perform normalization on the stereo file.
