### ISSUE TITLE
lrt doesn't work and Error opening output file

### ISSUE THREAD

**Issue by JonRFleming** [slhck/ffmpeg-normalize#259]
--loudness-range-target doesn't work either.

"C:\Users\<me>\AppData\Local\Programs\Python\Python312\Scripts\ffmpeg-normalize.exe" "C:\Temporary\Test.mp4" -o "C:\Temporary\Normalized\" -lrt 10.0 -c:a aac -b:a 128k -ofmt mp4 -ext mp4
WARNING: Input file had loudness range of 10.0. This is larger than the loudness range target (7.0). Normalization will revert to dynamic mode. Choose a higher target loudness range if you want linear normalization. Alternatively, use the --keep-loudness-range-target or --keep-lra-above-loudness-range-target option to keep the target loudness range from the input.
WARNING: In dynamic mode, the sample rate will automatically be set to 192 kHz by the loudnorm filter. Specify -ar/--sample-rate to override it.
ERROR: Error while running command 'C:\Program Files\FFMpeg\ffmpeg.exe' -hide_banner -y -i 'C:\Temporary\Test.mp4' -filter_complex '[0:1]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=-0.1:measured_i=-25.59:measured_lra=10.0:measured_tp=-8.14:measured_thresh=-36.11:linear=true:print_format=json[norm1]' -map_metadata 0 -map_metadata:s:a:0 0:s:a:0 -map_metadata:s:v:0 0:s:v:0 -map_chapters 0 -map 0:0 -c:v copy -map '[norm1]' -c:a:0 pcm_s16le -c:s copy 'C:\Users\<me>\AppData\Local\Temp\tmpetrlow8e\out.0 -c:a aac -b:a 128k -ofmt mp4 -ext mp4'! Error: Error running command ['C:\\Program Files\\FFMpeg\\ffmpeg.exe', '-hide_banner', '-y', '-i', 'C:\\Temporary\\Test.mp4', '-filter_complex', '[0:1]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=-0.1:measured_i=-25.59:measured_lra=10.0:measured_tp=-8.14:measured_thresh=-36.11:linear=true:print_format=json[norm1]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_metadata:s:v:0', '0:s:v:0', '-map_chapters', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:a:0', 'pcm_s16le', '-c:s', 'copy', 'C:\\Users\\<me>\\AppData\\Local\\Temp\\tmpetrlow8e\\out.0 -c:a aac -b:a 128k -ofmt mp4 -ext mp4']: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Temporary\Test.mp4':
Metadata:
major_brand     : isom
minor_version   : 512
compatible_brands: isomiso2avc1mp41
title           : Temp
artist          : VideoProc Converter
encoder         : Lavf57.73.100
comment         : Temp
genre           : DVD
Duration: 00:51:44.80, start: 0.000000, bitrate: 1737 kb/s
Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 960x720 [SAR 1:1 DAR 4:3], 1600 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
Metadata:
handler_name    : VideoHandler
vendor_id       : [0][0][0][0]
Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
Metadata:
handler_name    : SoundHandler
vendor_id       : [0][0][0][0]
[AVFormatContext @ 000002235bbebf80] Unable to choose an output format for 'C:\Users\<me>\AppData\Local\Temp\tmpetrlow8e\out.0 -c:a aac -b:a 128k -ofmt mp4 -ext mp4'; use a standard extension for the filename or specify the format manually.
[out#0 @ 000002235bbab8c0] Error initializing the muxer for C:\Users\<me>\AppData\Local\Temp\tmpetrlow8e\out.0 -c:a aac -b:a 128k -ofmt mp4 -ext mp4: Invalid argument
Error opening output file C:\Users\<me>\AppData\Local\Temp\tmpetrlow8e\out.0 -c:a aac -b:a 128k -ofmt mp4 -ext mp4.
Error opening output files: Invalid argument

**Comment by slhck** [comment]
When you set the `-o` option it must be an output file, not a directory.

Next time, please follow the issue template. Thanks!
