### ISSUE TITLE
Movie loudness compression

### ISSUE THREAD

**Issue by pannal** [slhck/ffmpeg-normalize#26]
I've used this for an old series which has really bad sound mixing (starts with Doctor) on the remastered BluRay/DVD releases:

`ffmpeg-normalize --verbose --merge --force --acodec libfdk_aac --ebu --extra-options "-threads 4 -b:a 224k -filter:a 'compand=0|0:1|1:-90/-900|-70/-70|-30/-9|0/-3:6:0:0:0'" *.mkv`

Perhaps this helps someone who doesn't only want to normalize, but to even out peaks and lows, also.

**Comment by slhck** [comment]
Sorry for never getting back – thanks for the example! I added it to the README in case it helps someone. I can see how the compand filter can come in useful in combination with loudness normalization.

**Comment by Nottt** [comment]
Is this something that can be safely run against any input? i.e to batch process files

That being said, most input would be bluray/dvd mkv files

**Comment by slhck** [comment]
I wouldn't recommend it. Applying a dynamic compression filter on professionally produced content will most likely do more harm than good. Just use EBU R 128 to get the same levels across all content.
