### ISSUE TITLE
Metadata flags like "Commentary" or "Visual Impaired" get lost.

### ISSUE THREAD

**Issue by joshinils** [slhck/ffmpeg-normalize#265]
Using https://mkvtoolnix.download/downloads.html I can edit the flags for different audio tracks.

For files where I've set the Commentary or Visual Impaired flags, they are lost after normalization.

To reproduce you can set the commentary flag on an MKV file and normalize, afterward it is back to the pre-filled value of "No" in mkvtoolnix-gui.

**Comment by joshinils** [comment]
Thankfully I've also renamed the tracks, so the info is not really lost for all the files I have.
But I'd have to programmatically parse my track titles and re-set the flags, which I'm willing to do in future anyway, since I want to also set the "original language" flag for all of them.

**Comment by slhck** [comment]
Could you please supply a sample and the full debugging output for troubleshooting purposes?

This is, essentially, an ffmpeg issue. If metadata is not copied despite setting the metadata copy flag, there [might be an alternative solution](https://video.stackexchange.com/a/26076/525).

**Comment by slhck** [comment]
Closed for the time being, please report back if you have a sample so we can diagnose ffmpeg's behavior.
