### ISSUE TITLE
Add ffmpeg -ac channel downmixing to output options

### ISSUE THREAD

**Issue by wyup** [slhck/ffmpeg-normalize#268]
When I try ffmpeg-normalize -i video-with-multichannel-audio.mp4 -ac 2 -o normalized.mkv, outputs error:

ffmpeg-normalize: error: unrecognized arguments: -ac 2

I would like to include ffmpeg -ac channel downmix to ffmpeg-normalize options to normalize from multichannel audio without having to downmix manually beforehand.

Hoping it is useful,
Thanks

**Comment by wyup** [comment]
okay, I see answer in previous issue

**Comment by slhck** [comment]
Glad you got it solved.

For others who may stumble upon this, are you referring to the extra output options?

**Comment by wyup** [comment]
yes
