### ISSUE TITLE
run_command with default raw=True, why?

### ISSUE THREAD

**Issue by pannal** [slhck/ffmpeg-normalize#27]
Hey,

It's bad practice to use popen with a string instead of a list of arguments, as argument escaping isn't done in that case.

Why is `raw=True` by default on run_command? This creates all sorts of issues. 

You should simply provide a list of arguments, the executable being the first item in that list, to the popen call. That takes care of proper escaping.

That way, this would work:
`ffmpeg-normalize --verbose --merge --force --acodec libfdk_aac --ebu --extra-options "-threads 4 -b:a 224k -filter:a compand=0|0:1|1:-90/-900|-70/-70|-30/-9|0/-3:6:0:0:0"`

Instead now I have to single quote the compand filter to not get a wrong call to ffmpeg.

If you do not want that (due to popen replacing os.system perhaps?), you can use this to sanitize the argument list to a string:
``` 
import sys
mswindows = (sys.platform == "win32")

if mswindows:
    from subprocess import list2cmdline
    quote_args = list2cmdline
else:
    # POSIX
    from pipes import quote

    def quote_args(seq):
        return ' '.join(quote(arg) for arg in seq)
```

**Comment by slhck** [comment]
Thanks for the heads-up. Why? I think at the time I wrote this I wasn't too familiar with Python, and so I just stuck with that piece of code. Maybe I had some issues with quoting … I don't remember.

I'll try and have a look at how to improve that part.

**Comment by pannal** [comment]
Because otherwise arguments aren't necessarily properly escaped. When passed a list popen ensures the parameters are properly escaped. When passed a string it tends to error out on more complex ones (see my example above).

I can supply a pull request once I get around forking this project. I'd like to have the compand filter natively inside as it really helps with normalization.

**Comment by slhck** [comment]
> I can supply a pull request once I get around forking this project.

If you have some fixes for that `popen` call, I'd welcome that! Otherwise I can have a look in the next days.

> I'd like to have the compand filter natively inside as it really helps with normalization.

This could indeed be made an extra option to activate. It would certainly help with some material, especially with EBU normalization.

**Comment by slhck** [comment]
Fixed now in the latest version.

**Comment by slhck** [comment]
To be more precise: I pass all the extra options as a single entry of the command argument list. Not sure if that helps in your case. I guess one could figure out a better way of specifying the extra options, or map some of them directly.
