### ISSUE TITLE
Multiply file size up to 10 times

### ISSUE THREAD

**Issue by tiofabby** [slhck/ffmpeg-normalize#29]
Hello
I am trying to normalize mp3 files (Stereo, 32 bits, 44 MHz).
When I do so with ffmpeg-normalize, the new normalized files are up to 10 times bigger in term of size.
Is there a way to avoid this?
Thank you
Fabrice

**Comment by slhck** [comment]
The default output is PCM stereo audio in a WAV file, which is uncompressed, hence the big file size. The reason for doing so is that the output should be lossless by default.

If you want smaller output files, you have to re-encode the files and compress them using a lossy audio codec such as AAC or MP3. You can do this by setting the `--acodec` option and possibly some extra options like audio bitrate (e.g. 192 kBit/s for AAC which should be transparent):

    ffmpeg-normalize --acodec libfdk_aac --extra-options "-b:a 192k" /path/to/input.mp3

Note that if you want to normalize a bunch of MP3 files without actually modifying the stream or re-compression, you should probably use [MP3Gain](http://mp3gain.sourceforge.net/) instead.

**Comment by tiofabby** [comment]
Excellent, Thanks a lot for your very detailed and quick feedback!!

**Comment by stragu** [comment]
Anyone ending up here looking for a fix and getting and error of the type `unrecognized arguments: --acodec`, know that we now have to use the flags `-c:a` or `--audio-codec` to specify the audio codec, and `-b:a` or `--audio-bitrate` for bitrate.
