### ISSUE TITLE
mp4 files collecting a lot of artifacts on merge

### ISSUE THREAD

**Issue by FuzzyWobble** [slhck/ffmpeg-normalize#30]
[test_mp4.zip](https://github.com/slhck/ffmpeg-normalize/files/1134091/test_mp4.zip)

**Comment by slhck** [comment]
I cannot reproduce this here with the file you gave me and a recent ffmpeg version.

    ffmpeg-normalize rcqjcasmof.mp4 --merge

Please update your ffmpeg and try again. If it doesn't work, please show what version of ffmpeg you're using and what command you're running exactly.

**Comment by FuzzyWobble** [comment]
> ffmpeg version 3.3 Copyright (c) 2000-2017 
> built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)

...still getting lots of artifacts :(

**Comment by slhck** [comment]
Can you download the latest version from [here](https://www.johnvansickle.com/ffmpeg/) and run the following command?

```bash
ffmpeg -i rcqjcasmof.mp4 -c:v copy -filter:a loudnorm normalized-rcqjcasmof.mp4
```
Unfortunately I cannot reproduce this, neither running it with `ffmpeg-normlaize` nor manually with the above command. I *do* see the issues in the file that you sent.

**Comment by FuzzyWobble** [comment]
ok fixed. yes, you need the most extremely current version of ffmpeg or bad things happen :U

thanks for the help!
