### ISSUE TITLE
How to update to the latest branch?

### ISSUE THREAD

**Issue by invokers123** [slhck/ffmpeg-normalize#31]
I am sorry I am new to all this.

I have successfully installed the script using the following command:

pip install ffmpeg-normalize

I was just wondering how to update the same script.

Like we can do with apt-get update

 have tried pip update, but there is no such command.

Thanks for the great script!

**Comment by slhck** [comment]
Glad you like it. Simple:

    pip install --upgrade ffmpeg-normalize

See `pip install -h` for help. I know it's confusing if you're used to `apt`.
