### ISSUE TITLE
Cant do -ux or -uxf?

### ISSUE THREAD

**Issue by Saltystew** [slhck/ffmpeg-normalize#33]
I would like to normalize audio contained in video files and I want the process to merge the audio back into the video container and then remove the old (not normalized) file.

This is all I get when I run it

![shot_170731_010756](https://user-images.githubusercontent.com/20447447/28763512-b817ed16-758c-11e7-9a4d-6ea3220995ca.png)

**Comment by slhck** [comment]
What happens when you just run ffmpeg-normalize on one file, with the `-uv` flags or `-ux`?

Note that you cannot use the "merge" (`-u`) and "no prefix" (`-x`) options at the same time, as ffmpeg cannot overwrite the input file (see #22). It should actually give you an error message in that case. I have some plans on solving this, with a temporary file, but the current version requires you to either write to another output directory `-o`

**Comment by Saltystew** [comment]
-uv works fine as expected but -ux gives me the same output as the previous image I posted.

![shot_170731_032515](https://user-images.githubusercontent.com/20447447/28767081-5549605c-75a0-11e7-9cbe-da56462fa1ee.png)


If I can't do some form of -ux or -uf, normalize the audio and merge it back while also removing the old file, atm then this is sadly pretty useless to me.

I have thousands of files I'd like to use this on atm and afterwards I'd like to just have it set to run automatically every once and a while.

**Comment by slhck** [comment]
It seems that it doesn't know the `-x` option. What is your ffmpeg-normalize version? (Run with `--version`.) Make sure you are using the latest one by upgrading with pip: `pip install --upgrade ffmpeg-normalize`.

You could run it in a batch script, call ffmpeg-normalize on each file with merging, write that to a `normalized` folder (option `-o`), delete the original, and move the output back to the parent folder.

**Comment by Saltystew** [comment]
Yea for w.e reason I was on 0.2.3, I'm on 0.5.2 now.

Yea the whole another folder option wont work for me in this situation, that'd screw up so much other stuff going on. Plus even if it didn't interfere with other things going on, I don't have time to worry about deleting the original and moving shit around as often as I'd need this to run. 

This isn't a must have, just nice to have, so I'll just wait and when/if you ever get around to that temp file method you mentioned I'll try messing with it again.

Thanks for the help.

**Comment by slhck** [comment]
If you put this in a batch file it's literally two extra lines apart from the call to the tool.

I have just created a new version (0.6.0) that implements the possibility to overwrite the input file directly (use `-uxf`).
