### ISSUE TITLE
Environment vars and tildes are not expanded when looking for ffmpeg

### ISSUE THREAD

**Issue by Mathijsz** [slhck/ffmpeg-normalize#36]
For example, `ffmpeg.exe` resides in `/home/<username>/bin` and `$PATH` is defined in `~/.bashrc` as follows:
`PATH="~/bin:$PATH"`

Results in the following error:
`ERROR: Could not find ffmpeg in your $PATH. Please install ffmpeg from http://ffmpeg.org`

**Comment by slhck** [comment]
Also pushed to pip as v0.7.1 now.
