### ISSUE TITLE
Invalid cross-device link

### ISSUE THREAD

**Issue by igitur** [slhck/ffmpeg-normalize#39]
I'm running this command on my xubuntu box. The `/tmp` and `/media/pool` (where my target files are) are on separate file systems.

```
$ ffmpeg-normalize -vuxf "20170927--Why_Farming_Is_Broken_And_Always_Has_Been--UkMZJrbCRdQ.mp4"
INFO: reading file 1 of 1 - 20170927--Why_Farming_Is_Broken_And_Always_Has_Been--UkMZJrbCRdQ.mp4
INFO: mean volume: -18.8
INFO: max volume: 0.0
INFO: file needs -7.199999999999999 dB gain to reach -26.0 dB
WARNING: Merging audio with the original file, but encoder was automatically chosen. Set '--acodec' to overwrite.
Traceback (most recent call last):
  File "/usr/local/bin/ffmpeg-normalize", line 11, in <module>
    load_entry_point('ffmpeg-normalize==0.7.2', 'console_scripts', 'ffmpeg-normalize')()
  File "/usr/local/lib/python3.5/dist-packages/ffmpeg_normalize/__main__.py", line 479, in main
    ffmpeg_normalize.run()
  File "/usr/local/lib/python3.5/dist-packages/ffmpeg_normalize/__main__.py", line 448, in run
    input_file.move_tmp_file()
  File "/usr/local/lib/python3.5/dist-packages/ffmpeg_normalize/__main__.py", line 364, in move_tmp_file
    os.rename(self.output_file, self.input_file)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpf2hta6d7.mp4' -> '20170927--Why_Farming_Is_Broken_And_Always_Has_Been--UkMZJrbCRdQ.mp4'
```

From what I gather, the `os.rename` method can't be used across different file systems.

**Comment by slhck** [comment]
Interesting, thanks for reporting this. I have to check again, maybe `shutil.move` works in this case.

In the meantime you could write to a `normalized-...` file and do the `mv` manually later.

**Comment by igitur** [comment]
I'll test with `shutil.move` and let you know.

**Comment by igitur** [comment]
PS: My use case is that I download all my YouTube subscriptions overnight (cheaper bandwidth over here) and then watch them from local files. But the audio levels vary drastically, which is why I'm looking at this tool. So the workaround you mentioned (to use the prefix) will work, but will complicate my scripts even more. I'd prefer to avoid that.

**Comment by slhck** [comment]
I pushed a change using `shutil.move`. Please let me know if that works for you.

**Comment by igitur** [comment]
Successful, thanks!
