### ISSUE TITLE
Can this be used to RMS normalize across multiple files?

### ISSUE THREAD

**Issue by markreg** [slhck/ffmpeg-normalize#43]
I have a folder of music from different albums all at varying volumes. Is it possible to use ffmpeg-normalize to analyze the RMS volume in all files and increase/alter the volume accordingly?

Thanks!

**Comment by slhck** [comment]
Yes, that is basically default behavior:

    ffmpeg-normalize --verbose --dir --level -23 --acodec aac --extra-options "-b:a 192k" *.m4a

This will write AAC-encoded files to a folder called `normalized`. You may want to adjust the level depending on your preferences.

If you have music as MP3s, you may want to use [MP3Gain](http://mp3gain.sourceforge.net/) instead. It does not re-encode the files and instead sets the normalization factor in the files' metadata.

**Comment by markreg** [comment]
Ok, I'll try that and report back.

Since I'm outputting the music from a raspberry pi over HDMI to a home theater a/v receiver (which I presume has some kind of amplifier) what is the appropriate volume to normalize the files to relative to the volume of the receiver?

For example, if -45dB on my receiver is approximately the volume at which I can reasonably hear the non-normalized music collection, what level would work best with ffmpeg-normalize? Thanks.

**Comment by michaelcrossland** [comment]
Try using -15 db then if that's to high try stepping it down by -5 db. As
music will lower to low to fast. -26 and below it to much in most cases. I
found that out with my ps3.

**Comment by markreg** [comment]
I'm having trouble with an error:

`[1;31mERROR[1;0m: file *.mp3 does not exist, will skip`

**Comment by michaelcrossland** [comment]
it's because n windws yu can't use *.mp3 to run on more then one file. you
have use that in a bat file.

When you're short of everything but the enemy, you're in combat.
Don't run, you'll only die tired. - Army Snipers

**Comment by slhck** [comment]
Something like:

    for %%A IN (*.mp3) DO ffmpeg-normalize … "%%A"

**Comment by michaelcrossland** [comment]
yes that wuld qrk if you want wav files not mp3's. you would have to
add ffmpeg-normalize -u -v -a mp3 -e "-b:a 128k -ar 44100"

When you're short of everything but the enemy, you're in combat.
Don't run, you'll only die tired. - Army Snipers

**Comment by markreg** [comment]
Ok, the for loop worked well.

One last question, is there a way for ffmpeg-normalize to simply copy the file if no normalization needs to occur (rather than skipping the file)? Otherwise I need to copy the files which were not normalized from the original directory which may be forgotten. Thanks.

**Comment by michaelcrossland** [comment]
If you are using it windows short answer is no. Because there is no ez way
to get the text output from the command prompt or Powershell you would need
to do that under a unix like os.

**Comment by slhck** [comment]
> is there a way for ffmpeg-normalize to simply copy the file if no normalization needs to occur

No, but this would be a nice feature addition. I'll put it on the list.
