### ISSUE TITLE
Normalization With --no-prefix Flag Automatically Writes to /tmp

### ISSUE THREAD

**Issue by keithwoelke** [slhck/ffmpeg-normalize#47]
When running your utility with --no-prefix, the scripts generates the normalized file in /tmp and then overrides the old file with the new file. This works well for most of my needs. However, some video files on my system are ~8 GB. My free space on my / partition is around 6 GB. This means I am unable to use the --no-prefix flag on any files which are larger than around 6 GB. Is there any way to get around this limitation using ffmpeg-normalize itself?

I ended up writing a script to rename the normalized files, but it would have been nice not to need to. :-)

**Comment by slhck** [comment]
The script uses the standard Python `tempfile` library which [should respect the `TMPDIR` environment variable](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp).

Thus, if you set `export TMPDIR=/path/to/wherever`, `ffmpeg-normalize` should use that for storing temporary files.

**Comment by keithwoelke** [comment]
Hmmm... that may work reasonably well. Unfortunately, that file is generated using some sort of random hash? That means it may make manual clean-up a bit more challenging if you're in the progress of normalizing multiple files.

One benefit of my current approach is if I stop normalizing midway through a file, then restart my script later, it will simply overwrite the previous file and then rename it once complete.

I suppose the ideal use case for me would be a flag to allow generating the file in the same directory with a prefix, then overwrite/rename once done.

**Comment by slhck** [comment]
… or you could write everything to a new directory using the `--dir` option, then `mv` everything from that directory to the parent, which would overwrite the original files.

**Comment by keithwoelke** [comment]
I don't think that would gain me anything over my current scripting (because I'm working in more than one directory):

find /media/Storage/Videos/ -type f \! -name "normalized-*" -execdir ffmpeg-normalize -level -23 --ebu -e "-ar 44100" --verbose --merge --force "{}" \; -execdir sh -c 'rename -force "s/^normalized-//g" normalized-"$(basename "$1")"' sh "{}" \;;

It would be worse, actually. I would still need to remove the directory in addition to moving the files.

**Comment by slhck** [comment]
I'm tempted to close this — I've just released version 1.0 with significant improvements and changes to how input/output is handled.

You can now directly specfiy the output file name for any given input file name, e.g.:

    ffmpeg-normalize <input1> <input2> -o <output1> <output2>
