### ISSUE TITLE
Windows file in use error

### ISSUE THREAD

**Issue by quaffapint** [slhck/ffmpeg-normalize#51]
Just testing on a sample mkv file...

`ffmpeg-normalize test.mkv -c:a aac -b:a 192k -f`

...getting...
`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\username\\AppData\\Local\\Temp\\tmpxcqezk6w.mkv' -> 'output.mkv'`

**Comment by slhck** [comment]
I don't have Windows to test here, will be able to do that next week only. In principle it writes to a temporary file, and once that writing process (through ffmpeg) is done, the temporary file is moved to the specified output file.

Which process do you think could be using it?

Can you please show the entire command and run it with `--debug --verbose`? (I assume the file is not actually called `output.mkv` since that is not specified in your command.)

**Comment by quaffapint** [comment]
I think the temp file handle isn't closed out when it's trying to move it. Here's the full log..

`c:\Programs\ffmpeg\bin>ffmpeg-normalize DTS-HRA5.1_VC1-23.976.mkv -c:a aac -b:a 192k -f --debug --verbose
DEBUG: Parsing streams of DTS-HRA5.1_VC1-23.976.mkv
DEBUG: Running command: ['C:\\Programs\\ffmpeg\\bin\\ffmpeg', '-i', 'DTS-HRA5.1_VC1-23.976.mkv', '-t', '0', '-map', '0', '-f', 'null', 'NUL']
DEBUG: Stream parsing command output:
DEBUG: ffmpeg version 3.4.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, matroska,webm, from 'DTS-HRA5.1_VC1-23.976.mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2016-02-08T17:01:53.000000Z
  Duration: 00:00:44.96, start: 0.003000, bitrate: 20042 kb/s
    Stream #0:0: Video: vc1 (Advanced) (WVC1 / 0x31435657), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 17021257
      BPS-eng         : 17021257
      DURATION        : 00:00:44.961000000
      DURATION-eng    : 00:00:44.961000000
      NUMBER_OF_FRAMES: 1078
      NUMBER_OF_FRAMES-eng: 1078
      NUMBER_OF_BYTES : 95661597
      NUMBER_OF_BYTES-eng: 95661597
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-02-08 17:01:53
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-02-08 17:01:53
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: dts (DTS-HD HRA), 96000 Hz, 5.1(side), fltp (default)
    Metadata:
      title           : DTS-HD Audio
      BPS             : 3018000
      BPS-eng         : 3018000
      DURATION        : 00:00:44.960000000
      DURATION-eng    : 00:00:44.960000000
      NUMBER_OF_FRAMES: 4215
      NUMBER_OF_FRAMES-eng: 4215
      NUMBER_OF_BYTES : 16961160
      NUMBER_OF_BYTES-eng: 16961160
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-02-08 17:01:53
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-02-08 17:01:53
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (vc1 (native) -> wrapped_avframe (native))
  Stream #0:1 -> #0:1 (dts (dca) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: wrapped_avframe, yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc (default)
    Metadata:
      BPS             : 17021257
      BPS-eng         : 17021257
      DURATION        : 00:00:44.961000000
      DURATION-eng    : 00:00:44.961000000
      NUMBER_OF_FRAMES: 1078
      NUMBER_OF_FRAMES-eng: 1078
      NUMBER_OF_BYTES : 95661597
      NUMBER_OF_BYTES-eng: 95661597
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-02-08 17:01:53
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-02-08 17:01:53
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc57.107.100 wrapped_avframe
    Stream #0:1(eng): Audio: pcm_s16le, 96000 Hz, 5.1(side), s16, 9216 kb/s (default)
    Metadata:
      title           : DTS-HD Audio
      BPS             : 3018000
      BPS-eng         : 3018000
      DURATION        : 00:00:44.960000000
      DURATION-eng    : 00:00:44.960000000
      NUMBER_OF_FRAMES: 4215
      NUMBER_OF_FRAMES-eng: 4215
      NUMBER_OF_BYTES : 16961160
      NUMBER_OF_BYTES-eng: 16961160
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-02-08 17:01:53
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-02-08 17:01:53
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc57.107.100 pcm_s16le
frame=    0 fps=0.0 q=0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

DEBUG: Found video stream at index 0
DEBUG: Found audio stream at index 1
INFO: Normalizing file DTS-HRA5.1_VC1-23.976.mkv (1 of 1)
DEBUG: Running normalization for DTS-HRA5.1_VC1-23.976.mkv
DEBUG: Parsing normalization info for DTS-HRA5.1_VC1-23.976.mkv
INFO: Running first pass loudnorm filter for stream 1
DEBUG: Running command: ['C:\\Programs\\ffmpeg\\bin\\ffmpeg', '-nostdin', '-y', '-i', 'DTS-HRA5.1_VC1-23.976.mkv', '-filter_complex', '[0:1]loudnorm=i=-24.0:lra=7.0:tp=-2.0:offset=0.0:print_format=json', '-vn', '-sn', '-f', 'null', 'NUL']
DEBUG: Loudnorm first pass command output:
DEBUG: ffmpeg version 3.4.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, matroska,webm, from 'DTS-HRA5.1_VC1-23.976.mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2016-02-08T17:01:53.000000Z
  Duration: 00:00:44.96, start: 0.003000, bitrate: 20042 kb/s
    Stream #0:0: Video: vc1 (Advanced) (WVC1 / 0x31435657), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 17021257
      BPS-eng         : 17021257
      DURATION        : 00:00:44.961000000
      DURATION-eng    : 00:00:44.961000000
      NUMBER_OF_FRAMES: 1078
      NUMBER_OF_FRAMES-eng: 1078
      NUMBER_OF_BYTES : 95661597
      NUMBER_OF_BYTES-eng: 95661597
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-02-08 17:01:53
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-02-08 17:01:53
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: dts (DTS-HD HRA), 96000 Hz, 5.1(side), fltp (default)
    Metadata:
      title           : DTS-HD Audio
      BPS             : 3018000
      BPS-eng         : 3018000
      DURATION        : 00:00:44.960000000
      DURATION-eng    : 00:00:44.960000000
      NUMBER_OF_FRAMES: 4215
      NUMBER_OF_FRAMES-eng: 4215
      NUMBER_OF_BYTES : 16961160
      NUMBER_OF_BYTES-eng: 16961160
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-02-08 17:01:53
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-02-08 17:01:53
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:1 (dca) -> loudnorm
  loudnorm -> Stream #0:0 (pcm_s16le)
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Audio: pcm_s16le, 192000 Hz, 5.1(side), s16, 18432 kb/s (default)
    Metadata:
      encoder         : Lavc57.107.100 pcm_s16le
size=N/A time=00:00:01.80 bitrate=N/A speed=3.59x
size=N/A time=00:00:04.50 bitrate=N/A speed=4.49x
size=N/A time=00:00:07.20 bitrate=N/A speed=4.76x
size=N/A time=00:00:10.00 bitrate=N/A speed=4.94x
size=N/A time=00:00:12.70 bitrate=N/A speed=5.01x
size=N/A time=00:00:15.40 bitrate=N/A speed=5.05x
size=N/A time=00:00:18.10 bitrate=N/A speed=5.07x
size=N/A time=00:00:20.50 bitrate=N/A speed=5.01x
size=N/A time=00:00:22.90 bitrate=N/A speed=4.98x
size=N/A time=00:00:25.50 bitrate=N/A speed=4.99x
size=N/A time=00:00:28.00 bitrate=N/A speed=4.98x
size=N/A time=00:00:29.90 bitrate=N/A speed=4.88x
size=N/A time=00:00:31.90 bitrate=N/A speed=4.81x
size=N/A time=00:00:33.90 bitrate=N/A speed=4.75x
size=N/A time=00:00:36.00 bitrate=N/A speed= 4.7x
size=N/A time=00:00:38.10 bitrate=N/A speed=4.67x
size=N/A time=00:00:40.50 bitrate=N/A speed=4.67x
size=N/A time=00:00:44.96 bitrate=N/A speed=4.86x
size=N/A time=00:00:44.96 bitrate=N/A speed=4.85x
video:0kB audio:101160kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_loudnorm_0 @ 00000263e2cd3880]
{
        "input_i" : "-9.40",
        "input_tp" : "-0.08",
        "input_lra" : "4.00",
        "input_thresh" : "-19.40",
        "output_i" : "-23.20",
        "output_tp" : "-13.23",
        "output_lra" : "3.30",
        "output_thresh" : "-33.20",
        "normalization_type" : "dynamic",
        "target_offset" : "-0.80"
}

DEBUG: Loudnorm stats parsed: {"input_i": "-9.40", "input_tp": "-0.08", "input_lra": "4.00", "input_thresh": "-19.40", "output_i": "-23.20", "output_tp": "-13.23", "output_lra": "3.30", "output_thresh": "-33.20", "normalization_type": "dynamic", "target_offset": "-0.80"}
INFO: Running second pass for DTS-HRA5.1_VC1-23.976.mkv
DEBUG: Running command: ['C:\\Programs\\ffmpeg\\bin\\ffmpeg', '-y', '-nostdin', '-i', 'DTS-HRA5.1_VC1-23.976.mkv', '-filter_complex', '[0:1]loudnorm=i=-24.0:lra=7.0:tp=-2.0:offset=0.0:measured_i=-9.4:measured_lra=4.0:measured_tp=-0.08:measured_thresh=-19.4:linear=true:print_format=json[norm1]', '-map_metadata', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:s', 'copy', '-c:a', 'aac', '-b:a', '192k', 'C:\\Users\\username\\AppData\\Local\\Temp\\tmpycl_e_vo.mkv']
DEBUG: Normalization command output:
DEBUG: ffmpeg version 3.4.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, matroska,webm, from 'DTS-HRA5.1_VC1-23.976.mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2016-02-08T17:01:53.000000Z
  Duration: 00:00:44.96, start: 0.003000, bitrate: 20042 kb/s
    Stream #0:0: Video: vc1 (Advanced) (WVC1 / 0x31435657), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 17021257
      BPS-eng         : 17021257
      DURATION        : 00:00:44.961000000
      DURATION-eng    : 00:00:44.961000000
      NUMBER_OF_FRAMES: 1078
      NUMBER_OF_FRAMES-eng: 1078
      NUMBER_OF_BYTES : 95661597
      NUMBER_OF_BYTES-eng: 95661597
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-02-08 17:01:53
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-02-08 17:01:53
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: dts (DTS-HD HRA), 96000 Hz, 5.1(side), fltp (default)
    Metadata:
      title           : DTS-HD Audio
      BPS             : 3018000
      BPS-eng         : 3018000
      DURATION        : 00:00:44.960000000
      DURATION-eng    : 00:00:44.960000000
      NUMBER_OF_FRAMES: 4215
      NUMBER_OF_FRAMES-eng: 4215
      NUMBER_OF_BYTES : 16961160
      NUMBER_OF_BYTES-eng: 16961160
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-02-08 17:01:53
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-02-08 17:01:53
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:1 (dca) -> loudnorm
  Stream #0:0 -> #0:0 (copy)
  loudnorm -> Stream #0:1 (aac)
Output #0, matroska, to 'C:\Users\username\AppData\Local\Temp\tmpycl_e_vo.mkv':
  Metadata:
    creation_time   : 2016-02-08T17:01:53.000000Z
    encoder         : Lavf57.83.100
    Stream #0:0: Video: vc1 (Advanced) (WVC1 / 0x31435657), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      BPS             : 17021257
      BPS-eng         : 17021257
      DURATION        : 00:00:44.961000000
      DURATION-eng    : 00:00:44.961000000
      NUMBER_OF_FRAMES: 1078
      NUMBER_OF_FRAMES-eng: 1078
      NUMBER_OF_BYTES : 95661597
      NUMBER_OF_BYTES-eng: 95661597
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-02-08 17:01:53
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-02-08 17:01:53
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 96000 Hz, 5.1(side), fltp, 192 kb/s (default)
    Metadata:
      encoder         : Lavc57.107.100 aac
[matroska @ 0000022639e82c80] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frame=   51 fps=0.0 q=-1.0 size=     522kB time=00:00:02.15 bitrate=1986.6kbits/s speed= 4.3x
frame=  101 fps=101 q=-1.0 size=     944kB time=00:00:04.18 bitrate=1848.4kbits/s speed=4.18x
frame=  155 fps=103 q=-1.0 size=    1556kB time=00:00:06.48 bitrate=1965.6kbits/s speed=4.32x
frame=  213 fps=106 q=-1.0 size=    2374kB time=00:00:08.87 bitrate=2191.3kbits/s speed=4.43x
frame=  268 fps=107 q=-1.0 size=    6733kB time=00:00:11.19 bitrate=4928.8kbits/s speed=4.47x
frame=  324 fps=108 q=-1.0 size=   13147kB time=00:00:13.52 bitrate=7962.4kbits/s speed= 4.5x
frame=  377 fps=108 q=-1.0 size=   18881kB time=00:00:15.70 bitrate=9850.3kbits/s speed=4.48x
frame=  428 fps=107 q=-1.0 size=   24511kB time=00:00:17.86 bitrate=11239.1kbits/s speed=4.46x
frame=  486 fps=108 q=-1.0 size=   30836kB time=00:00:20.23 bitrate=12484.3kbits/s speed=4.49x
frame=  542 fps=108 q=-1.0 size=   37847kB time=00:00:22.61 bitrate=13710.3kbits/s speed=4.52x
frame=  602 fps=109 q=-1.0 size=   44265kB time=00:00:25.07 bitrate=14459.6kbits/s speed=4.55x
frame=  660 fps=110 q=-1.0 size=   50873kB time=00:00:27.48 bitrate=15161.3kbits/s speed=4.57x
frame=  714 fps=110 q=-1.0 size=   56192kB time=00:00:29.76 bitrate=15467.8kbits/s speed=4.57x
frame=  764 fps=109 q=-1.0 size=   60950kB time=00:00:31.84 bitrate=15681.6kbits/s speed=4.54x
frame=  816 fps=109 q=-1.0 size=   66395kB time=00:00:33.99 bitrate=16000.2kbits/s speed=4.52x
frame=  868 fps=108 q=-1.0 size=   72745kB time=00:00:36.19 bitrate=16465.8kbits/s speed=4.51x
frame=  922 fps=108 q=-1.0 size=   76983kB time=00:00:38.43 bitrate=16409.3kbits/s speed=4.51x
frame=  976 fps=108 q=-1.0 size=   82151kB time=00:00:40.69 bitrate=16537.7kbits/s speed=4.51x
frame= 1030 fps=108 q=-1.0 size=   88527kB time=00:00:42.98 bitrate=16871.0kbits/s speed=4.51x
frame= 1078 fps=108 q=-1.0 Lsize=   94560kB time=00:00:44.96 bitrate=17229.5kbits/s speed= 4.5x
video:93420kB audio:1057kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.088395%
[Parsed_loudnorm_0 @ 0000022639ea3820]
{
        "input_i" : "-9.41",
        "input_tp" : "-0.08",
        "input_lra" : "4.00",
        "input_thresh" : "-19.41",
        "output_i" : "-24.01",
        "output_tp" : "-14.68",
        "output_lra" : "4.00",
        "output_thresh" : "-34.01",
        "normalization_type" : "linear",
        "target_offset" : "0.01"
}
[aac @ 0000022639e95460] Qavg: 262.908

DEBUG: Moving temporary file from C:\Users\username\AppData\Local\Temp\tmpycl_e_vo.mkv to normalized\DTS-HRA5.1_VC1-23.976.mkv
ERROR: Error while running command ['C:\\Programs\\ffmpeg\\bin\\ffmpeg', '-y', '-nostdin', '-i', 'DTS-HRA5.1_VC1-23.976.mkv', '-filter_complex', '[0:1]loudnorm=i=-24.0:lra=7.0:tp=-2.0:offset=0.0:measured_i=-9.4:measured_lra=4.0:measured_tp=-0.08:measured_thresh=-19.4:linear=true:print_format=json[norm1]', '-map_metadata', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:s', 'copy', '-c:a', 'aac', '-b:a', '192k', 'C:\\Users\\username\\AppData\\Local\\Temp\\tmpycl_e_vo.mkv']!
Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\username\\AppData\\Local\\Temp\\tmpycl_e_vo.mkv' -> 'normalized\\DTS-HRA5.1_VC1-23.976.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\ffmpeg_normalize\_media_file.py", line 233, in _second_pass
    shutil.move(temp_file.name, self.output_file)
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\shutil.py", line 559, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\username\\AppData\\Local\\Temp\\tmpycl_e_vo.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\Scripts\ffmpeg-normalize-script.py", line 11, in <module>
    load_entry_point('ffmpeg-normalize==1.0.2', 'console_scripts', 'ffmpeg-normalize')()
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\ffmpeg_normalize\__main__.py", line 315, in main
    ffmpeg_normalize.run_normalization()
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\ffmpeg_normalize\_ffmpeg_normalize.py", line 155, in run_normalization
    media_file.run_normalization()
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\ffmpeg_normalize\_media_file.py", line 116, in run_normalization
    self._second_pass()
  File "c:\users\username\appdata\local\programs\python\python36-32\lib\site-packages\ffmpeg_normalize\_media_file.py", line 237, in _second_pass
    os.remove(temp_file.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\username\\AppData\\Local\\Temp\\tmpycl_e_vo.mkv'

c:\Programs\ffmpeg\bin>`

**Comment by slhck** [comment]
Yes, that seems plausible. Working on a fix!

**Comment by slhck** [comment]
Pushed version 1.0.3 that does not actually create any open file pointer in Python, but instead lets ffmpeg create it by its path.

Couldn't test on Windows, but runs fine on *nix, so I'd appreciate if you could check. Otherwise I'll do so Monday.

**Comment by quaffapint** [comment]
Can confirm the error no longer occurs and everything is now working (testing on Windows 10 x64). Thanks for the quick fix.
