### ISSUE TITLE
Temporary directory option

### ISSUE THREAD

**Issue by mdcollins05** [slhck/ffmpeg-normalize#53]
Would it be possible to have a setting for the temporary file(s) location? The reason I ask is because I use this script on a machine with very little local disk space and I access the files over NFS. I haven't run into an issue yet but I'm only testing with smaller files at the moment.

Thanks for the awesome script, I've been looking for something like this for a while now.
Sorry for opening multiple issues in the last day or so!

**Comment by slhck** [comment]
Sure, this is already possible by setting the respective environment variable (`TMP`, `TEMP` or `TEMPDIR`):

https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir

Let me know if that doesn't work for you. I'll document it in the `README`.

**Comment by slhck** [comment]
Done. Note that the directory specified by the environment variable has to exist — otherwise it'll fall back to the system defaults.

**Comment by mdcollins05** [comment]
Thanks! I didn't realize that was an option.

Cheers!
