### ISSUE TITLE
Can't find ffmpeg on Windows

### ISSUE THREAD

**Issue by quaffapint** [slhck/ffmpeg-normalize#57]
Have ffmpeg in my system path in windows 8.1. Windows command line sees it fine.

Using version 1.05 of your script finds ffmpeg and works fine. Version 1.06/1.07 both complain during install that it can't find it. Version 1.08 installs, but it says that the ffmpeg executable is not a valid file, the path that it lists is the correct path.

I downgraded back to 1.05, which is still working.

**Comment by slhck** [comment]
Yes, there was a bug in 1.06/1.07 that ran some executable check upon install, which shouldn't happen. I'll check what the difference between 1.05 and 1.08 is. Thanks for the report!
