### ISSUE TITLE
MP4 with AC3 audio: Could not parse loudnorm stats

### ISSUE THREAD

**Issue by mdcollins05** [slhck/ffmpeg-normalize#61]
Thanks for the awesome program! I've been looking for something like this for a while.

I've been going through my videos and while are working, I'm having an issue with a few of them. It'll exit with "Could not parse loudnorm stats". All of my videos are MP4s with AC3 audio, so it's not that. Some are mono, some stereo, some 5.1. None of the failures seem consistent there.

I've looked through the code and found it'll give that error when either A: it couldn't find the parsed loudnorn info in the command output or B: it isn't valid JSON. Both of which don't seem to be the issue. I'm not really sure what would cause the issue.

- OS: Debian 8.8
- Python 2.7.9
- ffmpeg 3.4.2
- Command: ffmpeg-normalize "${file}" -c:a ac3 -ar 48000 -o "${file}" -f -v -d
- Full (2mb!) debug output is here: https://gist.githubusercontent.com/mdcollins05/eec5ea3a1a8da602f206e4b391a2be79/raw/e2b4075a80e6628e27564dbe358a82d1db4f76d6/output.log

**Comment by slhck** [comment]
I think it has to do with the warnings printed, since the script tries to parse all lines from `parsed_loudnorm` until the end, so it captures the warnings, too.

**Comment by slhck** [comment]
Should work now, let me know if you still experience issues with this particular file.
