### ISSUE TITLE
Normalisation fail with default audio codec

### ISSUE THREAD

**Issue by aviolo** [slhck/ffmpeg-normalize#63]
Hello,

I discover this library to normalize media.
I have ubuntu 16.04. The python version is 3.5.2, ffmpeg version is 3.4.2.
I try to normalize the media that you can found [here](https://www.ubicast.eu/media/downloads/Test/test_h264_opus.mkv). The audio codec is opus, video codec is h264 and container is matroska.

When I launch the command below, I have an error:
```
ffmpeg-normalize test_h264_opus.mkv
Invalid encoder type 'pcm_s16le
```
and the stdout show this command:
`Error while running command ['/home/aviolo/bin/ffmpeg', '-y', '-nostdin', '-i', 'test_h264_opus.mkv', '-filter_complex', '[0:0]loudnorm=measured_i=-99.0:tp=-2.0:measured_tp=-99.0:measured_thresh=-70.0:lra=7.0:linear=true:i=-24.0:offset=0.0:measured_lra=0.0:print_format=json[norm0]', '-map_metadata', '0', '-map', '0:1', '-c:v', 'copy', '-map', '[norm0]', '-c:s', 'copy', '-c:0', 'pcm_s16le', '/tmp/q70bryk4.mkv']!`

but when I launch the command below, I don't have an error:
`ffmpeg-normalize test_h264_opus.mkv -c:a pcm_s16le`

When I add debug mode on this command, I have that:
`Running command: ['/home/aviolo/bin/ffmpeg', '-y', '-nostdin', '-i', 'test_h264_opus.mkv', '-filter_complex', '[0:0]loudnorm=print_format=json:linear=true:i=-24.0:offset=0.0:lra=7.0:measured_tp=-99.0:measured_lra=0.0:tp=-2.0:measured_thresh=-70.0:measured_i=-99.0[norm0]', '-map_metadata', '0', '-map', '0:1', '-c:v', 'copy', '-map', '[norm0]', '-c:s', 'copy', '-c:a', 'pcm_s16le', '/tmp/0smisstr.mkv']`

The difference between the both command debug is:  
`-c:0', 'pcm_s16le`
`-c:a', 'pcm_s16le`

I wonder if that's normal or if it's more of a bug.

**Comment by slhck** [comment]
Good observation! It shouldn't be `-c:0`, but rather `-c:a` so that it applies to all audio streams. `-c:0` would be the video stream. I'll look into this later.

In the meantime you can use `-c:a pcm_s16le` as you suggested, or any other encoder you'd like.

**Comment by slhck** [comment]
The problem seems to be that your input file has the audio stream at index 0 and the video stream at index 1. Usually, it's the other way around. When writing the output file, it assigns the video stream to output ID 0 and then later tries to apply the PCM codec to that output ID, which is wrong.

I'll have to re-think how the streams are being written …

**Comment by slhck** [comment]
Should work now in v1.2.0, if not, please supply a sample file so I can test again.

**Comment by aviolo** [comment]
Thank you for your answers and the fix. I will try it.
