### ISSUE TITLE
Error when install module

### ISSUE THREAD

**Issue by aviolo** [slhck/ffmpeg-normalize#68]
Hello,

I got the last version (1.3.0) but when I start python3 setup.py install, the installation returns this issue:
```
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from ffmpeg_normalize import __version__ as version
  File "/home/builders/ubuntu-14-04/0_build_0/ffmpeg-normalize/build/ffmpeg-normalize/ffmpeg_normalize/__init__.py", line 1, in <module>
    from ._ffmpeg_normalize import FFmpegNormalize
  File "/home/builders/ubuntu-14-04/0_build_0/ffmpeg-normalize/build/ffmpeg-normalize/ffmpeg_normalize/_ffmpeg_normalize.py", line 4, in <module>
    from tqdm import tqdm
ImportError: No module named 'tqdm'
```
I know that module tqdm is not installed and when I install it everything is ok. The problem is that this dependency shouldn't be required in the setup module. I build ffmpeg-normalize in a debian package and the builder calls `setup.py clean` and crashes because tqdm is not installed on the system used to build the package.

regards,

Anthony

**Comment by slhck** [comment]
I think the problem is rather that I do a:

    from ffmpeg_normalize import __version__ as version

at the top of the setup script to get the version. This requires tqdm although at that point it would not yet be needed.

I'll think about a fix, hang on.

**Comment by slhck** [comment]
Please try with the new setup script – it doesn't perform the import and therefore should not require any additional dependencies. Thanks for the bug report!

**Comment by aviolo** [comment]
Thanks for the quick fix, building the debian package works fine.
