### ISSUE TITLE
Non-monotonous DTS in output stream / Queue input is backward in time

### ISSUE THREAD

**Issue by jim1001** [slhck/ffmpeg-normalize#71]
[ Win 7] Your operating system
[ 3.6.5rc1] Your Python version / distribution
[N-89803 ] Your ffmpeg version

When running 
`ffmpeg -i file.webm -filter:a volumedetect -f null NUL`

on a file produced by ffmpeg-normalize I see the message

> Application provided invalid, non monotonically increasing dts to muxer in stream 1:

Running the same command on the  original file (before normalization) doesn’t produce these messages. Do you know why they appear and if they indicate a problem?

I can see messages in the output of ffmpeg-normalize
> Queue input is backward in time

and

> Non-monotonous DTS in output stream 0:1

but don't know how to interpret them.

I attach debug info from the  ffmpeg-normalize command and the output from the volumedetect filter on the before and after files.

Thank you.

[log.txt](https://github.com/slhck/ffmpeg-normalize/files/1998770/log.txt)

**Comment by slhck** [comment]
It's not really a problem. Are you experiencing any issues with the files?

**Comment by slhck** [comment]
ffmpeg sometimes prints warnings like this when the timestamps of subsequent frames are non-monotonously increasing (i.e. going backwards in time or staying the same). This may happen with particular combinations of containers and video/audio streams. In your case it likely happens because the output is not a real container (i.e. `NUL`) – for some codecs you want your output container to be a seekable file, which `NUL` isn't.

**Comment by jim1001** [comment]
> In your case it likely happens because the output is not a real container (i.e. NUL) – for some codecs you want your output container to be a seekable file, which NUL isn't.

OK - that could explain the messages from _volumedetect_ filter command I used.

However these errors / warnings: 

> Queue input is backward in time | Non-monotonous DTS in output stream 0:1

can be seen when running the command
```
ffmpeg-normalize --debug infile.webm -c:a libvorbis --normalization-type peak --target-level -1 
--output outfile.webm
```
I ran with `--debug` to follow your advice in submitting an issue. Without that the command doesn't output anything to the cmd window,

Anyhow, pleased it's nothing to worry about and thanks for your time in answering.
