### ISSUE TITLE
Progress is not working correctly

### ISSUE THREAD

**Issue by paulprovost** [slhck/ffmpeg-normalize#74]
Hi there,

Thanks for the script. It is working great, except for one thing. The progress bar (--progress) does not update. It shows the following for a while:

    File:   0%|                                                  | 0/1 [00:00<?, ?it/s]
    Stream 1/1:   0%|                                            | 0/100 [00:00<?, ?it/s]

And then the script is done.

What could be wrong? `ffmpeg` version? I installed from linuxbrew.

- Operating system: Ubuntu 17.10
- Python version / distribution: Python 2.7.15 in a venv
- ffmpeg:

        ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers
        built with gcc 5.4.1 (Ubuntu 5.5.0-1ubuntu2) 20171010
        configuration: --prefix=/home/paul/.linuxbrew/Cellar/ffmpeg/4.0 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=gcc-5 --host-cflags= --host-ldflags= --enable-gpl --enable-libfdk-aac --enable-libmp3lame --enable-libx264 --enable-libxvid --disable-lzma --enable-nonfree

- Command:

        ffmpeg-normalize movie.mp4 -v -pr -c:a libfdk_aac -b:a 192k --extension mp4

**Comment by slhck** [comment]
Thanks for the report! I was unable to reproduce the behavior with ffmpeg 4.0 and Python 2.7.15 under macOS. I may try under Linux as soon as I get to it.

The only reason for the command not being updated would be the `run_ffmpeg_command` function not yielding the progress.

Does the problem also occur with Python 3?

**Comment by paulprovost** [comment]
Yes, same with `python 3.6.5`. I seem to recall having the same issue on macOS, but I'm not 100% sure. I'll give it a shot tonight.

**Comment by slhck** [comment]
Interesting, I was not able to repro it. If you are up for debugging you may peek into the function I mentioned earlier and check if it is even receiving any standard output from ffmpeg.

**Comment by paulprovost** [comment]
Just for additional info, I ran a normalization with `--debug` and the tail part looks like this:

    INFO: Running second pass for file.mp4                                                                 
    DEBUG: Running ffmpeg command: ['/home/me/.linuxbrew/bin/ffmpeg', '-y', '-nostdin', '-i', 'file.mp4', '-filter_complex',[0:1]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.0:measured_i=-15.48:measured_lra=19.5:measured_tp=2.49:measured_thresh=-27.18:linear=true:print_format=json[norm1]', '-map_metadata', '0', '-map_chapters', '0', '-map', '0:0', '-c:v', 'copy', '-map', '[norm1]', '-c:a', 'libfdk_aac', '-b:a', '192k', '-map', '0:2', '-c:s', 'copy', '/tmp/axuh3f48.mp4']                               
    File:   0%|                                                                                                    | 0/1 [25:53<?, ?it/snDEBUG: 
    Moving temporary file from /tmp/axuh3f48.mp4 to normalized/file.mp4                             
    DEBUG: Normalization finished                                                                                                        
    INFO: Normalized file written to normalized/blame.2017.720p.bluray.x264-ghouls.mp4                                                   
    File: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [1:18:43<00:00, 4723.39s/it]

The copy/paste might be screwed up, by that's pretty much what I got.

I'll try debugging tonight.

**Comment by slhck** [comment]
If you clone the source code and edit the file `lib/_cmd_utils.py`, at line 77 introduce a debugging statement:

```python
if not total_dur and CommandRunner.DUR_REGEX.search(line):
    total_dur = CommandRunner.DUR_REGEX.search(line).groupdict()
    total_dur = to_ms(**total_dur)
    import pdb; pdb.set_trace()
    continue
```

Then run:

    python2 -m ffmpeg_normalize <input> -pr

Does it ever stop?

**Comment by paulprovost** [comment]
Yes, it stops right at the beginning.

    WARNING: Output directory 'normalized' does not exist, will create
    File:   0%|                                                                                                                                    | 0/1 [00:00<?, ?it/s>
     /Users/me/dev/ffmpeg-normalize/ffmpeg_normalize/_cmd_utils.py(81)run_ffmpeg_command()                                                     | 0/100 [00:00<?, ?it/s]
    -> continue
    (Pdb)

**Comment by slhck** [comment]
I could now reproduce the issue with Python 3.6 under Linux, let me look into what causes it.

**Comment by paulprovost** [comment]
How did you get it to happen? Just curious...

**Comment by slhck** [comment]
When I was testing, I was using a file that actually completed much too fast for me to notice that the progress was not being updated. When I debug the lines that ffmpeg prints, it appears like the progress time is never even shown, and only once printed at the end, when the progress is 100%. I'll have to dig further. It may be a change of ffmpeg's behavior.

**Comment by xlJohnnyIcelx** [comment]
Just thought I'd chime in and say that I'm also having this issue on Windows.

**Comment by romanvbabenko** [comment]
Confirm. OSX 10.13.6, Python 3.6.5, ffmpeg version 4.0.2

**Comment by slhck** [comment]
I found the problem, which is ffmpeg writing its progress using carriage returns (`\r`), which do not trigger `.readline()`, so nothing is read until the process is completely finished.

I have tried to work around this and pushed my work in progress to another branch: https://github.com/slhck/ffmpeg-normalize/commit/c95e1a583fe4c4774a8cd85c081984591dd75995

… but the solution is not working in all cases. Sometimes (I guess there's some race condition?) the ffmpeg command exits too early, not returning all output.

**Comment by sampumon** [comment]
I would guess there's buffering somewhere down the pipe. Would ffmpeg's -progress option workaround this?

I tested it spits progress chunks into stdout with `-progress -`. One-line `\r` stats can be disabled with `-nostats`.

**Comment by slhck** [comment]
@sampumon Good idea – I never spotted that option. We could add `-nostats` and `-progress -` to the call, parse lines with `out_time`, and compare that with the total duration. Not sure if I'll find some time to work on that in the next weeks. One would need to make sure that these global flags are only added for the final conversion command to not add too much info to the output.

**Comment by slhck** [comment]
I fixed this in https://github.com/slhck/ffmpeg-normalize/commit/ff1d5145f4de5dd2e0f4d11baaf6704fdff221f4 (sorry, wrong issue reference in the commit). Thanks for your suggestion, @sampumon — that was the missing piece.
