### ISSUE TITLE
Converting multiple files at once and overwriting input files

### ISSUE THREAD

**Issue by iamrototo** [slhck/ffmpeg-normalize#75]
- Windows 10
- Python latest version 3.6.5
-- ffmpeg
ffmpeg version N-89951-g3caecf7ce8 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.2.0 (GCC)
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
libavutil      56.  7.100 / 56.  7.100
libavcodec     58.  9.100 / 58.  9.100
libavformat    58.  7.100 / 58.  7.100
libavdevice    58.  0.101 / 58.  0.101
libavfilter     7. 11.101 /  7. 11.101
libswscale      5.  0.101 /  5.  0.101
libswresample   3.  0.101 /  3.  0.101
libpostproc    55.  0.100 / 55.  0.100
 

I want to convert all the video and audio from folder and subfolder. I don't know if it's possible to do so but I tried at least in one folder with 2 files : .mp4 and .wav

ffmpeg-normalize *.wav *.mp4 -c:a aac -f
>> ERROR: file *.wav does not exist

DEBUG

DEBUG: found executable in path: C:\ffmpeg\bin\ffmpeg
DEBUG: found executable in path: C:\ffmpeg\bin\ffmpeg
DEBUG: Running command: ['C:\\ffmpeg\\bin\\ffmpeg', '-filters']
ERROR: FFmpegNormalizeError: file *.mp3 does not exist
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\Scripts\ffmpeg-normalize-script.py", line 11, in <module>
    load_entry_point('ffmpeg-normalize==1.3.4', 'console_scripts', 'ffmpeg-normalize')()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\ffmpeg_normalize\__main__.py", line 348, in main
    ffmpeg_normalize.add_media_file(input_file, output_file)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\ffmpeg_normalize\_ffmpeg_normalize.py", line 172, in add_media_file
    raise FFmpegNormalizeError("file " + input_file + " does not exist")
ffmpeg_normalize._errors.FFmpegNormalizeError: file *.mp3 does not exist

I tried by specifying the filename, is ok but it keeps creating a normalized folder and the new file are on it instead replacing the old one...

ffmpeg-normalize audio.wav video.mp4 -c:a aac -f
>> WARNING: Output directory 'normalized' does not exist, will create

(the debug is too long to be put here)

Thanks !

**Comment by slhck** [comment]
> I want to convert all the video and audio from folder and subfolder. I don't know if it's possible to do so but I tried at least in one folder with 2 files : .mp4 and .wav

>    ffmpeg-normalize *.wav *.mp4 -c:a aac -f

Windows does not support that format. The `*.wav` syntax is from Bash, and it expands to all files with the `.wav` extension.

I think in Windows you have to do something like this:

    for %%x in (*.wav *.mp4) do ffmpeg-normalize %%x -c:a aac -f

**Comment by iamrototo** [comment]
Good found, I indeed try using GitBash and it works ;-). However, I think I misunderstood the -f option. I have lot of files in lot of folder and wanted to normalize them by overwriting the original file. Seems the -f option just overwrite the normalized file in the default folder... I suppose that I have to make a script to manually compute the destination folder =/

I also found that the normalized files have all the same extension, .mkv

ffmpeg-normalize */*.wav */*.mp4 -c:a aac -f

If I do only the wav file 

 ffmpeg-normalize test2/audio.wav -o test2/audio.wav -f

then it's fine.

**Comment by slhck** [comment]
`-f` overwrites an already existing output file.

If you really want to overwrite each input file, you have to explicitly specify the output file name (with `-o`) to be the same as the input file name, **and** specify the `-f` parameter to overwrite the output file. 

You will then need to do it with a loop such as this (in Bash):

    for f in *.wav; do ffmpeg-normalize "$f" -o "$f" -f; done

… or similarly with Windows — basically set the output to the input file name.

> I also found that the normalized files have all the same extension, .mkv

See the README:

> The default output container is .mkv as it will support most input stream types. If you want a different output container, make sure that it supports your input file's video, audio, and subtitle streams (if any).

**Comment by iamrototo** [comment]
Thanks for your support ;-)
Yes indeed I will need to make a bash script to convert files by files.
I found a bit strange to not use the same container as the input file by default... as if you normalize a .wav, it makes sense to normalize it inside an another .wav, no ?

**Comment by iamrototo** [comment]
Get it thanks for the explanation. And thanks for your work because it saves literally my day !!!

**Comment by slhck** [comment]
You're most welcome! 👋

**Comment by michaelcrossland** [comment]
If any of the file names havr spaces in them then that will not work best
thing to always do with Windows batch files is to put (") around what your
working with. Like this ("*.mkv") that way when Windows passes the file
name it don't put bark.mkv when the full file name is bark at the moon.mkv

**Comment by Venryx** [comment]
> I think in Windows you have to do something like this:
> 
> ```
> for %%x in (*.wav *.mp4) do ffmpeg-normalize %%x -c:a aac -f
> ```

Just wanted to mention that, the syntax above did not work for me (in either cmd or powershell).

Specifically, it seems the `%%x` instances need to be just `%x`, like so: (in cmd, not powershell)
```
for %x in (*.wav *.mp4) do ffmpeg-normalize %x -c:a aac -f
```

In my case, I actually didn't need the format-conversion, so I used the slightly modified command below: (again, in cmd)
```
for %x in (*.wav *.mp4) do ffmpeg-normalize %x --keep-loudness-range-target -of Normalized_KeepRange
```

**Comment by slhck** [comment]
Thanks for the clarification!

There's a wiki that can be freely edited here: https://github.com/slhck/ffmpeg-normalize/wiki/examples#use-windows-loops-for-multiple-files — the command there seems to be correct.
