### ISSUE TITLE
[question] handle utf8 character

### ISSUE THREAD

**Issue by iamrototo** [slhck/ffmpeg-normalize#76]
Hello,

here is my config (that didn't change)
Windows 10
Python latest version 3.6.5
-- ffmpeg
ffmpeg version N-89951-g3caecf7ce8 Copyright (c) 2000-2018 the FFmpeg developers
[...]
libavutil 56. 7.100 / 56. 7.100
libavcodec 58. 9.100 / 58. 9.100
libavformat 58. 7.100 / 58. 7.100
libavdevice 58. 0.101 / 58. 0.101
libavfilter 7. 11.101 / 7. 11.101
libswscale 5. 0.101 / 5. 0.101
libswresample 3. 0.101 / 3. 0.101
libpostproc 55. 0.100 / 55. 0.100

Here is my issue:
I want to convert files but some are located in folder with chinese name (不 for example).
However, it not working as expected:

ffmpeg-normalize "Dict\不\audio.wav" -nt peak -t -20 -o "Dict\不\audio.wav" -f
DEBUG: found executable in path: C:\ffmpeg\bin\ffmpeg
DEBUG: found executable in path: C:\ffmpeg\bin\ffmpeg
DEBUG: Running command: ['C:\\ffmpeg\\bin\\ffmpeg', '-filters']
ERROR: FFmpegNormalizeError: file Dict\?\audio.wav does not exist
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\Scripts\ffmpeg-normalize-script.py", line 11, in <module>
    load_entry_point('ffmpeg-normalize==1.3.4', 'console_scripts', 'ffmpeg-normalize')()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\ffmpeg_normalize\__main__.py", line 348, in main
    ffmpeg_normalize.add_media_file(input_file, output_file)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\ffmpeg_normalize\_ffmpeg_normalize.py", line 172, in add_media_file
    raise FFmpegNormalizeError("file " + input_file + " does not exist")
ffmpeg_normalize._errors.FFmpegNormalizeError: file Dict\?\audio.wav does not exist

Is it a misconfig of my python or a mistake on this program code that do not handle UTF8 character ?
Thanks for your help

**Comment by slhck** [comment]
I cannot reproduce this problem here under Linux:

```
python3 -m ffmpeg_normalize 不
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/werner/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/werner/Documents/Projects/slhck/ffmpeg-normalize/ffmpeg_normalize/__main__.py", line 354, in <module>
    main()
  File "/home/werner/Documents/Projects/slhck/ffmpeg-normalize/ffmpeg_normalize/__main__.py", line 348, in main
    ffmpeg_normalize.add_media_file(input_file, output_file)
  File "/home/werner/Documents/Projects/slhck/ffmpeg-normalize/ffmpeg_normalize/_ffmpeg_normalize.py", line 180, in add_media_file
    mf = MediaFile(self, input_file, output_file)
  File "/home/werner/Documents/Projects/slhck/ffmpeg-normalize/ffmpeg_normalize/_media_file.py", line 41, in __init__
    self.parse_streams()
  File "/home/werner/Documents/Projects/slhck/ffmpeg-normalize/ffmpeg_normalize/_media_file.py", line 64, in parse_streams
    cmd_runner.run_command()
  File "/home/werner/Documents/Projects/slhck/ffmpeg-normalize/ffmpeg_normalize/_cmd_utils.py", line 115, in run_command
    raise RuntimeError("Error running command {}: {}".format(self.cmd, str(stderr)))
RuntimeError: Error running command ['/home/werner/bin/ffmpeg', '-i', '不', '-c', 'copy', '-t', '0', '-map', '0', '-f', 'null', '/dev/null']: ...
不: Invalid data found when processing input
``` 
What shell are you using? Perhaps you need to play around with the quoting, or Windows has general issues with Unicode here. I'm not sure, to be honest.

In any case, it's not a bug with the program, I'm afraid.

**Comment by michaelcrossland** [comment]
What you're running into is a Windows thing with batch files or even
powershell scripts. You have to do some googling but know I have seen how
to warp a file name that has those kind of character types in them. I can't
tell you off hand what is because I don't have any files like that myselfe
sorry.

**Comment by iamrototo** [comment]
Thanks all really appreciate your support. I tried with command, powershell, and even if they can display chinese character, it''s not working when I use ffmpeg normalize. However, I tried on MAC OS and it's fine. I suppose indeed that Windows do not manage correctly chinese character and therefore I got this issue. 

I suppose that we can tag this question as closed. Thanks

**Comment by michaelcrossland** [comment]
Your welcome sorry I couldn't be more help. I know I've seen stuff on the
net when I've looked for other Windows batch file stuff that shows how to
use Unicode characters in batch files. It's more trouble than it's worth on
Windows if you're system language is not set to one of those language's by
default.

**Comment by iamrototo** [comment]
I couldn't stand with this failure, so I search a bit more today and found a solution !!!!

1. The first step is to activate the support for UTF8 (still in beta but ...)
https://stackoverflow.com/questions/34510700/encoding-issue-when-using-native-cmd-command-from-powershell

2. The second step is to specify the output as UTF8 in the powershell script, My final script looks like this:

$OutputEncoding = [System.Text.Encoding]::Unicode
Get-ChildItem -path "./" -recurse | foreach ($_) {
    if ($_.Extension -eq ".wav") { 
     ffmpeg-normalize $_.FullName -nt peak -t -20 -o $_.FullName -f
    }
    if ($_.Extension -eq ".mp4") { 
     ffmpeg-normalize $_.FullName -c:a aac -nt peak -t -20 -o $_.FullName -f
    }
        if ($_.Extension -eq ".mp3") { 
     ffmpeg-normalize $_.FullName -c:a libmp3lame -nt peak -t -20 -o $_.FullName -f
    }
}

**Comment by slhck** [comment]
Thanks for the snipped, glad you got it working!

**Comment by michaelcrossland** [comment]
Glad you were able to work it out.
