### ISSUE TITLE
How to get a hold of you to talk about something I want to try to do?

### ISSUE THREAD

**Issue by michaelcrossland** [slhck/ffmpeg-normalize#77]
This not a bug or anything fell free to close this because I all need to know is how to try to get a hold of you to ask you something that I have got setup and working on my system but want to get your okay before I try to roll it out to the world.

Thank for your time,
Michael Crossland
CEO/Owner of
StarLight L.L.C

**Comment by slhck** [comment]
Feel free to send me an email at werner.robitza at Gmail!

**Comment by michaelcrossland** [comment]
Thanks for the info.
I will try to sit down here in the next day or two and try to spell out
what I have done and working on and see if you are okay with me doing it
before I release what I have done out on 5the net.
As your party of the whole package.

Thanks for your time,
Michael Crossland
CEO/Owner of StarLight L.L.C

When you're short of everything but the enemy, you're in combat.
Don't run, you'll only die tired. - Army Snipers
