### ISSUE TITLE
Progress not working

### ISSUE THREAD

**Issue by xlJohnnyIcelx** [slhck/ffmpeg-normalize#78]
If you want to report a bug, or have a specific question, please make sure to include this information:

- [ ] Your operating system: Windows 10
- [ ] Your Python version / distribution: 3.6
- [ ] Your ffmpeg version: 3.4
- [ ] The exact command you were trying to run: {ffmpeg-normalize "%%F" -nt peak -t -1 -c:a aac -b:a 512k -pr}
- [ ] Any output you get when running the command with the `--debug` flag: {argument -p/--print-stats: ignored explicit argument 'r'}

**Comment by slhck** [comment]
Thanks for submitting a bug report. I don't fully understand what's going on though; I cannot reproduce this with Python 3.6 under Linux, using the latest version. It seems to interpret `-pr` as `-p` with an argument option `r`, which is not what's specified.

What version of ffmpeg-normalize are you using? (Run with `--version`)

**Comment by xlJohnnyIcelx** [comment]
It says version 1.1.0 which I can now see is quite an old version. I'm guessing this was the issue I'm having?

**Comment by slhck** [comment]
Yes, please update to the most recent one!
