### ISSUE TITLE
Default output extension problem.

### ISSUE THREAD

**Issue by melaanya** [slhck/ffmpeg-normalize#79]
Hi! I think there is a small discrepancy in the readme of your project and in the help message. 

On the one hand, it is said in the help message that 

" -o OUTPUT [OUTPUT ...], --output OUTPUT [OUTPUT ...]
                        Output file names. Will be applied per input file.
                        
                        If no output file name is specified for an input file, the output files
                        will be written to the default output folder with the name `<input>.wav`. "

On the other hand, 

  -ext EXTENSION, --extension EXTENSION
                        Output file extension to use for output files that were not explicitly
                        specified. (Default: `mkv`)

And the actual output when there is no specified output file is in the .mkv format.

Sorry for not describing this in detail upon the first submit!

**Comment by slhck** [comment]
Could you please tell me what the discrepancy is?

**Comment by slhck** [comment]
I was waiting for a comment in order to get notified – I did not see the edit, sorry. Fixed now!
