### ISSUE TITLE
m3u as input, mp3 as output

### ISSUE THREAD

**Issue by montyz** [slhck/ffmpeg-normalize#81]
My desire is to be able to upload my playlist to https://mixcloud.com. They accept one large `mp3` file and an `m3u` file for track listing.

It would be great if I could feed a `.m3u` or `.m3u8` file to `ffmpeg-normalize` so it could normalize the input files, concatenate all the output, and then re-encode the output to mp3.

It seems to me that on the input side of things I could add a function that parsed the playlist and returned the list as expected for the loop in `__main__.py`. Seems like having it concatenate all the output to one file may be a little trickier.

Do you think this is an appropriate addition to your program? Alternatively I can write a script to parse a playlist and call ffmpeg directly with all the input args, normalization options, and the `concat` filter.

**Comment by slhck** [comment]
Thanks for this suggestion! This program assumes that you are using a simple `ffmpeg -i input` call, so in principle it should work with a M3U8 playlist — did it not work in your case? As far as I know (cannot check now), ffmpeg should read the playlist and automatically create a concatenated output file. So there's nothing preventing the same mechanism from being used with ffmpeg-normalize.

The main benefit of ffmpeg-normalize is that you can do the two required passes in one go. So if for some reason it doesn't read the M3U8 playlist properly, you could write a script that first concatenated it into a, say, WAV file, and then normalize that using ffmpeg-normalize.

**Comment by montyz** [comment]
Yeah, unfortunately `ffmpeg -i test.m3u` gives an error `test.m3u: Invalid data found when processing input` though I can play the playlist just fine.

My goal is to normalize the files before concatenating so each song will have similar levels in the final mix. Maybe I should normalize them all to .wav files, then concatenate, then encode back to mp3.

**Comment by slhck** [comment]
Yes, that seems like the best solution as a workaround.

If you have an example M3U8 file I can look into what the problem with ffmpeg is.

**Comment by montyz** [comment]
@slhck here's a playlist that will be availabe for the next 2 days, just two songs in it but demonstrates the problem.
https://transfer.sh/J3UGm/Practica-a.tgz

**Comment by slhck** [comment]
I think there are two issues:

1. Seems that you need to indicate to ffmpeg that the M3U8 file is to be parsed using the HLS demuxer (`ffmpeg -f hls -i input.m3u8`)
2. The individual segments specified in the M3U8 file need to be available through a server; reading from local files does not seem to be supported or disabled for security reasons ([long thread here](https://patchwork.ffmpeg.org/patch/3768/)).

I can have a more in-depth look in the coming days, a bit busy here, but converting/concatenating the referenced tracks in the M3U8 before ffmpeg conversion seems like the best option in the meantime.

**Comment by montyz** [comment]
OK, thanks for looking into this. I can certainly script around it. Feel free to close the ticket, it seems like it would be more work than it is worth.

**Comment by slhck** [comment]
Ok, thanks for your feedback!

**Comment by slhck** [comment]
I did some further checking. A valid M3U8 file that ffmpeg will read has to be specified as follows:

```
#EXTM3U
#EXTINF:10
file://path/to/file/test1.mp3
#EXTINF:10
file://path/to/file/test2.mp3
```

Then you can call `ffmpeg -f hls -i input.m3u8` to read it and output to whatever other format.
Local files have to be referenced with the `file` protocol; just specifying the path is disabled for security reasons.

**Comment by slhck** [comment]
PS: The `EXTINF` specifier has to include the duration of the file in seconds (in the above case set to 10).
