### ISSUE TITLE
Using Several Audio Codec Options

### ISSUE THREAD

**Issue by faxotherapy** [slhck/ffmpeg-normalize#82]
- OS X 10.11.6
- Python 3.7.0
- FFmpeg 4.0.2
- `ffmpeg-normalize -pr "$f" -vn -sn -mn -cn -c:a libvorbis -e='-q 6' -e='-ac 2' -of /tmp/`

What if I want to use several options with the audio codec. I tried several combinations, but it's only one of them (the last one) is taken account. For example, I'd like to have quality 6 and stereo during encoding.

I tried:
- `-e='-q 6' -e='-ac 2'`
- `-e='-ac 2' -e='-q 6' `
- `-e='-q 6 -ac 2'`

It's only the last option that is taken account.

Thanks for your help.

**Comment by slhck** [comment]
Your last example should work. Please run the command with `-v` and show the full output.

**Comment by slhck** [comment]
That said, do not use `-e=` but just

    -e "-q 6 -ac 2"

**Comment by faxotherapy** [comment]
I confirm the following works properly (whatever option order):
- `-e='-q 6 -ac 2'`
- `-e "-q 6 -ac 2"`

Thanks for your time.

**Comment by slhck** [comment]
You're welcome, thanks for testing it again!
