### ISSUE TITLE
Adding Normalised Track to Original Movie File?

### ISSUE THREAD

**Issue by faxotherapy** [slhck/ffmpeg-normalize#83]
If you want to report a bug, or have a specific question, please make sure to include this information:

- [X] Your operating system: `10.11.6`
- [X] Your Python version / distribution: `3.7.0`
- [X] Your ffmpeg version: `4.0.2`
- [x] The exact command you were trying to run
- [ ] Any output you get when running the command with the `--debug` flag

---

Wouldn't it be great if there were one further option to simply add the new normalised audio track to the original movie file? It's just a breeze to remove it later if one is no longer happy.

For example, to restore the original movie file, remove the added (third) normalised track with:
```shell
$ mkvmerge -i Input.mkv
$ mkvmerge -o Output.mkv -a \!3 Input.mkv
```

For the moment, I'm using a script to automate my requirement on a bunch of movies using `ffmpeg-normalize` and `mkvmerge`.

Thanks for your thoughts on this.

**Comment by slhck** [comment]
Thanks for the suggestion – that's a great idea! Maybe there could be a new `--keep-original` option that keeps the original audio streams intact.

I'll have to see when I will have time to implement it.

**Comment by go2tom42** [comment]
It this still a thing?

**Comment by slhck** [comment]
Sure. PRs are welcome. I didn't have time yet to look at this myself.

**Comment by igitur** [comment]
This was possible in version 0.7.3 with the `-u` option right? If so, did we actually lose this functionality with the upgrade to version 1?

**Comment by slhck** [comment]
I rewrote the entire thing with version 1 so it'd be more flexible. I added a new flag `-koa` or `--keep-original-audio` which copies the original audio streams.

**Comment by igitur** [comment]
I don't think that `--keep-original-audio` does what this issue is about. I believe this issue is about keeping the original video in the original file and merging the normalised audio into the original file.

**Comment by slhck** [comment]
> I believe this issue is about keeping the original video in the original file and merging the normalised audio into the original file

That has always been possible since v1.0.

The OP asked about *adding* the normalized audio track to the original file instead of overwriting the original audio. The option I added basically does that; it adds the original audio track back to the original file if needed to enable "going back" to the previous version.

**Comment by igitur** [comment]
OK, sorry then I misunderstood the issue. What is the syntax to do what I want, the equivalent of the `-u` switch in version 0.7.3?

**Comment by slhck** [comment]
You don't have to add anything. By default the script normalizes audio streams and copies everything else over to an MKV file.

**Comment by igitur** [comment]
Sorry for my persistence, but I clearly don't understand.

I was using `ffmpeg-normalize -vuxf myfile.mp4` up until v0.7.3. I want to normalise the audio, have it copied back into the original file, and keep the format as an `mp4`, not `mkv`. 

What are the appropriate flags in the latest version to do exactly the same? Would appreciate your help.

**Comment by slhck** [comment]
This should work:

```
ffmpeg-normalize myfile.mp4 -of myfile-normalized.mp4
```

As mentioned, the program automatically copies existing video streams to the output file. If you want to overwrite the original file, specify the same name as output format and use `-f`.
