### ISSUE TITLE
Need to fix script to work with 64 Bit builds of ffmpeg

### ISSUE THREAD

**Issue by michaelcrossland1979** [slhck/ffmpeg-normalize#84]
If you want to report a bug, or have a specific question, please make sure to include this information:

- [Windows 10 Pro build 17134.228 ] Your operating system
- [Python 2.7.13 ] Your Python version / distribution
- [ffmpeg version N-92000-g59256dea14 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (Rev2, Built by MSYS2 project)
  configuration:  --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --disable-debug --enable-ffnvcodec --enable-nvdec --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libx264 --enable-libx265 --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libaom --enable-version3 --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-libopenh264 --enable-libopenmpt --enable-librtmp --enable-librubberband --enable-libssh --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-opencl --enable-opengl --enable-libcodec2 --enable-libsrt --enable-ladspa --enable-openssl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags='-Wl,--allow-multiple-definition' --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 30.100 / 58. 30.100
  libavformat    58. 18.102 / 58. 18.102
  libavdevice    58.  4.103 / 58.  4.103
  libavfilter     7. 32.100 /  7. 32.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Hyper fast Audio and Video encoder ] Your ffmpeg version
- [ffmpeg-normalize -u -v -b -a aac -e "-b:a 96k -ar 44100" "%FILENAME3%" ] The exact command you were trying to run
- [Sorry I don't have the output due to needing to get videos uploaded to my server. But it said something at the end of the python script stuff, It said something about it not being a win32 app. If I get time I will try running it once more with a 64 bit build to get you the info you want. Maybe a few days before I can get it to you. ] Any output you get when running the command with the `--debug` flag

**Comment by slhck** [comment]
If you get an error about something not being a valid Win32 application, that relates to an executable, which I guess is `ffmpeg` in your case. It's not really a problem with the Python script itself. Please make sure that you can run a simple script like this:

```bash
python -c 'import subprocess; subprocess.check_output(["ffmpeg", "-h"])'
```

**Comment by michaelcrossland1979** [comment]
I will give that a shot shot here in a day or two with a 64 bit build of
ffmpeg and see what I get and let you know what I find out, so that you can
make note of note to run 64 bit only builds of ffmpeg on windows if that is
the case.
When you're short of everything but the enemy, you're in combat.
Don't run, you'll only die tired. - Army Snipers


[image: user image]
Michael Crossland
CEO & Owner of Starlight L.L.C
940-799-9192 michaelcrossland@gmail.com

**Comment by slhck** [comment]
Closing now, please send logs if you have them.
