### ISSUE TITLE
Need some help.

### ISSUE THREAD

**Issue by michaelcrossland** [slhck/ffmpeg-normalize#85]
Was asking this here because I don't want to hear from everyone and there dog over at the Python forums. Is it passable to install an older ver of your script using pip?

**Comment by slhck** [comment]
pip install 'ffmpeg-normalize==<version>'

Where `<version>` is the version number.

**Comment by michaelcrossland** [comment]
thanks. I didn't want to redo my scripts. I like some of what you have done
with the newer versions but you have changed some stuff with how files are
handled and named. make me have redo all of my scripts. If what I'm working
on works right I'll let you you see what I have done and let you make the
call if I can post for others to use.
Thanks for a great script and all you're hard work.

**Comment by slhck** [comment]
Thanks for the heads-up. I would however not endorse anything that uses the 0.x-version of ffmpeg-normalize. The 1.x version offers significantly more functionality and is more flexible. The file handling has not changed a lot, so any adaptations necessary should be minimal. If you need help adapting your script please let me know.

**Comment by michaelcrossland** [comment]
I has to with the fact that when you don't pass a file name and extension
that it will just spit out a wav file. the older one with the - o it will
just output a file of the same type and just add the normalize tag to the
name. that and what I'm working on is a package that can be used for those
of us that get are TV and movies from bittorrent. That way utorrent or
other programs can call this program and level there videos before adding
them to what ever form of entertainment setup they maybe using. if it works
then I'll send you a copy of the program and the raw source code as well so
that you could tell if it's okay to use and help me make it work better for
the new versions That you come up with.

**Comment by slhck** [comment]
If you want the new ffmpeg-normalize to always output WAV with the same name you can do that:

    ffmpeg-normalize test/test.mp4 -ext wav -of .

This will create a file called `test.wav` in the working directory. If you want a prefix `normalized-` you can easily add that while calling through a script:

    ffmpeg-normalize test/test.mp4 -o test/normalized-test.wav

**Comment by michaelcrossland** [comment]
okay well like I said let get this thing working right first then I will
let you take a look at it and then anything you could think of to make it
better I'm all ears. oh for right now this will only be a windows only
program. I'll look into trying to get it to work in Java or some other
ambiguous Universal programming language.

**Comment by slhck** [comment]
I do not have Windows so I cannot test a Windows application. But if the functionality consists of taking input files and calling the Python program, this can be easily done in a cross-platform manner… just to understand, this would be a GUI?

**Comment by michaelcrossland** [comment]
as of right now no it is not a gui app. I may add a gui later but for now
and what it's meant to do it doesn't really need a gui to make it work
right as it's an app that doesn't show a cli window when running.

**Comment by slhck** [comment]
Then I don't really understand the benefit of a separate application. What functionality specifically would your script enable that is not offered by `ffmpeg-normalize`?

**Comment by michaelcrossland** [comment]
as for what it does is package ffmpeg and Python and your script and a copy
of filebot in an exe that people can use to have utorrent or any other
torrent program that can run programs after a torrent has been downloaded
to auto run your script on the file once file it has renamed the TV episode
then if they have a NAS or other storage system setup moved the leveled TV
show to there set folder for that show and then run crawl on there Plex
server to have look for new files and add them to there Library.
It does what 3 other things do but all open-source and free to boot. And
before you say filebot isn't free only the new Windows store builds are
paid and I'm not using them I have forked the old Java version that was
free and open source software.

**Comment by michaelcrossland** [comment]
The older version of the script I'm using is the one I fixed to used EBU
the right way had to tweak it so that EBU would hit the right level of - 24
db. As for running the newest version of the script I'll work on getting it
in to the program once I can get this version to work right. Got get very
0.1 out before trying to hit it out of the park with a shitty version 1.0
sorry I'm not Billy Gates I take parade in getting it right not pushing it
out just because it's the "newest and greatest" and it don't work at all.
