### ISSUE TITLE
Keep original codec and bitrate

### ISSUE THREAD

**Issue by lucasmr** [slhck/ffmpeg-normalize#90]
When normalizing many files, instead of having to set the same codec and bitrate for all files, there should be an option to keep the original codec and bitrate from the original file. This would be great for batch conversions and saving space.

**Comment by slhck** [comment]
Thanks for the suggestion. While certainly useful, this is not easy to implement. Some points:

- Keeping the bitrate does not mean keeping the same quality, as files will have generation loss. So I'm hesitant to put that in as an option. The user should choose an appropriate bitrate or VBR factor for their conversions. It's definitely not a 1:1 mapping.
- You'd have to do quite a lot of manual mapping from input codecs and formats to output encoders and formats. I guess you could keep the same input format (e.g., `mp3`, `matroska`) by default, but then you'd have to first figure out what encoder to use for a given output format and instruct ffmpeg to use it.
- Robustness: What if the input file uses a codec that ffmpeg can decode but not encode?

PRs on how to handle this are welcome.

**Comment by BassThatHertz** [comment]
> * Keeping the bitrate does not mean keeping the same quality, as files will have generation loss. So I'm hesitant to put that in as an option. The user should choose an appropriate bitrate or VBR factor for their conversions. It's definitely not a 1:1 mapping.

Just being pedantic and make things 100% clear for whoever reads this - keeping the bitrate the same when encoding will not retain the audio quality **if** you're using a lossy encoder. If you're using a lossless encoder, you are keeping the bitrate the same ((unless you're reducing the bit depth, e.g. 24-bit WAV to 16-bit WAV) and maintaining the quality.

Another way of keeping the audio codec and bitrate the same whilst maintaining quality is by using `-c:a copy`, which leaves the audio as-is (i.e. no encoding). Unfortunately stream copying is not possible when using the `-filter` option (in this case `-filter:a loudnorm`). The best way to maintain quality whilst not having WAV-sized files is to use the FLAC (with `-compression_level 12` for the lowest file size) or ALAC encoder.

**Comment by slhck** [comment]
Very good suggestions, @BassThatHertz, thanks!

**Comment by homocomputeris** [comment]
@slhck In the current version, is it possible to pass `-compression_level 12` option manually?

**Comment by slhck** [comment]
Yes, see the extra output options: https://github.com/slhck/ffmpeg-normalize#output-format

**Comment by homocomputeris** [comment]
Thanks, I had missed it at first, that's why I deleted the comment.

**Comment by BassThatHertz** [comment]
Meyt iodine to be sg![image](https://user-images.githubusercontent.com/48166845/95800936-9ec00200-0cf0-11eb-9912-3f609ad35f72.jpeg)D and tr iiu the

**Comment by BassThatHertz** [comment]
Free rjd. T. I r yrrt .r not xbr uyor iroe

**Comment by slhck** [comment]
I decided that it's not worth implementing this due to the inherent complexity.
