### ISSUE TITLE
Default value for 'LOUDNESS_RANGE_TARGET' (7) causes random volume spikes?

### ISSUE THREAD

**Issue by ghost** [slhck/ffmpeg-normalize#91]
Using Loudnorm EBU, I've noticed that at the default -lrt value of seven or below, random volume spikes somtimes appear throughout the audio where there were none originally. 

Before normalization it would be like this:
_"This is a line of dialogue."_
And after normalization:
_"This is a line of dia**LOGUE**"_

At -lrt 8 and above I have not noticed this issue. So simply raising the loudness range seems to eliminate the problem. I'm guessing at lower values it compresses the audio levels to the point where it causes distortion. 

One solution would be to simply raise the default LRT to a higher value than seven. Maybe ten would be a good middle-ground?  From what I understand does the EBU standard not specify a recommended Loudness Range, and the ffmpeg default of seven may just be too low for regular use .

**Comment by kylophone** [comment]
Can you share the source?

**Comment by slhck** [comment]
Note that the default chosen in this script is the same as for the `loudnorm` filter:

```
loudnorm AVOptions:
  LRA               <double>     ..F.A.... set loudness range target (from 1 to 20) (default 7)
  lra               <double>     ..F.A.... set loudness range target (from 1 to 20) (default 7)
```

So it's likely that this is an upstream bug. But as Kyle mentioned, please share a sample and the full command you were using. You can run `ffmpeg-normalize` with the `--debug` option to print the exact commands that were run.
