### ISSUE TITLE
Truncate integrated loudness values greater than zero to zero to let hot files pass

### ISSUE THREAD

**Issue by jonzener** [slhck/ffmpeg-normalize#92]
If the measured integrated loudness if above 0, which can happen, (though doesn't sound pretty) then the file gets rejected by the loudnorm filter. 

For ex:
[loudnorm @ 0000017935516c00] Value 0.380000 for parameter 'measured_i' out of range [-99 - 0]

It would be preferable to truncate values greater than zero to zero so that the file could still pass.

Full example of error:
C:\Users\user1\Desktop>ffmpeg-normalize -o "VCR_2868037_out.mp3" -v -nt ebu -t -16 -tp -1.5 -lrt 8 --dual-mono -f -c:a libmp3lame -b:a 128K -e="-joint_stereo 1 -reservoir 1 -write_xing 0" -ar 44100 "VCR_2868037.mp3"
WARNING: Output file only supports one stream. Keeping only first audio stream.
INFO: Normalizing file VCR_2868037.mp3 (1 of 1)
INFO: Running first pass loudnorm filter for stream 0
INFO: Running second pass for VCR_2868037.mp3
ERROR: Error while running command ['C:\\Program Files (x86)\\FFmpeg for Audacity\\ffmpeg', '-y', '-nostdin', '-i', 'VCR_2868037.mp3', '-filter_complex', '[0:0]loudnorm=i=-16.0:lra=8.0:tp=-1.5:offset=0.0:measured_i=0.38:measured_lra=1.4:measured_tp=8.05:measured_thresh=-9.63:linear=true:print_format=json:dual_mono=true[norm0]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_chapters', '0', '-c:v', 'copy', '-map', '[norm0]', '-c:a', 'libmp3lame', '-b:a', '128K', '-ar', '44100', '-c:s', 'copy', '-joint_stereo', '1', '-reservoir', '1', '-write_xing', '0', 'C:\\Users\\user1\\AppData\\Local\\Temp\\aeqyct1_.mp3']!
Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36\Scripts\ffmpeg-normalize-script.py", line 11, in <module>
    load_entry_point('ffmpeg-normalize==1.3.9', 'console_scripts', 'ffmpeg-normalize')()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36\lib\site-packages\ffmpeg_normalize-1.3.9-py3.6.egg\ffmpeg_normalize\__main__.py", line 378, in main
    ffmpeg_normalize.run_normalization()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36\lib\site-packages\ffmpeg_normalize-1.3.9-py3.6.egg\ffmpeg_normalize\_ffmpeg_normalize.py", line 174, in run_normalization
    media_file.run_normalization()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36\lib\site-packages\ffmpeg_normalize-1.3.9-py3.6.egg\ffmpeg_normalize\_media_file.py", line 132, in run_normalization
    for _ in self._second_pass():
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36\lib\site-packages\ffmpeg_normalize-1.3.9-py3.6.egg\ffmpeg_normalize\_media_file.py", line 301, in _second_pass
    raise e
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36\lib\site-packages\ffmpeg_normalize-1.3.9-py3.6.egg\ffmpeg_normalize\_media_file.py", line 287, in _second_pass
    for progress in cmd_runner.run_ffmpeg_command():
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36\lib\site-packages\ffmpeg_normalize-1.3.9-py3.6.egg\ffmpeg_normalize\_cmd_utils.py", line 88, in run_ffmpeg_command
    raise RuntimeError("Error running command {}: {}".format(self.cmd, str("\n".join(stderr))))
RuntimeError: Error running command ['C:\\Program Files (x86)\\FFmpeg for Audacity\\ffmpeg', '-y', '-nostdin', '-i', 'VCR_2868037.mp3', '-filter_complex', '[0:0]loudnorm=i=-16.0:lra=8.0:tp=-1.5:offset=0.0:measured_i=0.38:measured_lra=1.4:measured_tp=8.05:measured_thresh=-9.63:linear=true:print_format=json:dual_mono=true[norm0]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_chapters', '0', '-c:v', 'copy', '-map', '[norm0]', '-c:a', 'libmp3lame', '-b:a', '128K', '-ar', '44100', '-c:s', 'copy', '-joint_stereo', '1', '-reservoir', '1', '-write_xing', '0', 'C:\\Users\\user1\\AppData\\Local\\Temp\\aeqyct1_.mp3']: ffmpeg version N-92932-g038d291b70 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181201
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 25.100 / 56. 25.100
libavcodec     58. 43.100 / 58. 43.100
libavformat    58. 25.100 / 58. 25.100
libavdevice    58.  6.101 / 58.  6.101
libavfilter     7. 46.101 /  7. 46.101
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100
[mp3 @ 00000179354fba80] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'VCR_2868037.mp3':
Duration: 00:08:57.10, start: 0.000000, bitrate: 128 kb/s
Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
[loudnorm @ 0000017935516c00] Value 0.380000 for parameter 'measured_i' out of range [-99 - 0]
Last message repeated 1 times
[loudnorm @ 0000017935516c00] Error setting option measured_i to value 0.38.
[Parsed_loudnorm_0 @ 0000017935516b00] Error applying options to the filter.
[AVFilterGraph @ 000001793551c9c0] Error initializing filter 'loudnorm' with args 'i=-16.0:lra=8.0:tp=-1.5:offset=0.0:measured_i=0.38:measured_lra=1.4:measured_tp=8.05:measured_thresh=-9.63:linear=true:print_format=json:dual_mono=true'
Error initializing complex filters.
Result too large

**Comment by kylophone** [comment]
Yeah, this is a limitation of of the ffmpeg filter. I'm actually not sure how an IL > 0.0 is possible. Tested with full scale white noise gives me an IL of -1.6. 

`ffmpeg -f lavfi -i anoisesrc=color=white -t 60 -af ebur128 -f null -`

**Comment by jonzener** [comment]
Yes it's definitely a limitation of the filter. However if programatically
a number greater than 0 could be truncated to zero instead of being passed
on above zero, that would "solve" the problem.

Obviously the issue truly needs to be fixed in the file, but it would be
better to let a too hot file pass than not pass at all.

Here's what such a file "looks like":
[image: image.png]

**Comment by slhck** [comment]
What would be the best way to deal with that problem in this script? Changing the IL to 0 if greater than 0?

**Comment by jonzener** [comment]
Exactly.

**Comment by jonzener** [comment]
Werner thank you very much! Truly appreciate your attention and willing response! Confirmed with the same file that all is passing without error now:

c:\Users\user1\Desktop>ffmpeg-normalize -o VCR_2868037_out.mp3 -v -nt ebu -t -16 -tp -1.2 -lrt 8 --dual-mono -f -c:a libmp3lame -b:a 128K -e="-joint_stereo 1 -reservoir 1 -write_xing 0" -ar 44100 VCR_2868037.mp3
WARNING: Output file only supports one stream. Keeping only first audio stream.
INFO: Normalizing file VCR_2868037.mp3 (1 of 1)
INFO: Running first pass loudnorm filter for stream 0
INFO: Running second pass for VCR_2868037.mp3
WARNING: Input file had measured input loudness greater than zero (input_i), capping at 0
INFO: Normalized file written to VCR_2868037_out.mp3

**Comment by slhck** [comment]
Thanks for immediately testing!

I noticed I forgot to replace a value in the code, but it's probably a very rare error anyway.

That said, it'd still be interesting to know why this happens, but that is a bug report for FFmpeg.
