### ISSUE TITLE
logic to support opus 2.0 and 5.1 input by default

### ISSUE THREAD

**Issue by Nottt** [slhck/ffmpeg-normalize#98]
By default ffmpeg libopus needs to use different commands to output 2.0 or 5.1 correctly and using the correct settings.

I'd like to have some kind of logic to apply this based if the input is 2.0 or 5.1 so this command would just work out of the box for any input:

```
ffmpeg-normalize -v *.mkv -c:a libopus
```

A example of the relevant error if your input is 5.1 with that command is: 

```
[libopus @ 0x71eae00] Invalid channel layout 5.1(side) for specified mapping family -1.
Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
```

For 5.1 we need [to explicitly specify "-mapping_family 1" to let ffmpeg use newer surround api of libopus](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libopusenc.c#L336) and maybe even 2.0, but not sure on that. 

And also `-af "channelmap=channel_layout=5.1"` added to the ffmpeg command so it fixes the channel layout issue.

```
-e='-af "channelmap=channel_layout=5.1" -mapping_family 1'
```

If you use this you'll fail with this: 

```
Filtergraph 'channelmap=channel_layout=5.1' was specified through the -vf/-af/-filter option for output stream 0:0, which is fed from a complex filtergraph. 
-vf/-af/-filter and -filter_complex cannot be used together for the same stream.
```

We need some logic to apply the 5.1 settings to 5.1 input only.

I believe Opus is a awesome codec, that is also a [RFC standard](https://tools.ietf.org/html/rfc6716) and worthy of this effort. Who doesn't want to output a modern, open source, web compatible, high quality loud normalized file easily?

**Comment by slhck** [comment]
Yeah, specifying extra filters is not possible since I'm already “using up” the existing filter chain.

Note that FFmpeg help says:

> Set channel mapping family to be used by the encoder. The default value of -1 uses mapping family 0 for mono and stereo inputs, and mapping family 1 otherwise. The default also disables the surround masking and LFE bandwidth optimzations in libopus, and requires that the input contains 8 channels or fewer.

So the `-mapping_family 1` option *should* be used automatically for 5.1 input. I could however reproduce a problem with a 5.1 file that failed with:

```
➜ ffmpeg -y -i bbb.mp4 -vn -map 0:a:1 -c:a libopus -t 1 out.opus
…
[libopus @ 0x7fabe2808c00] Invalid channel layout 5.1(side) for specified mapping family -1.
```

One workaround was to use the `channelmap=channel_layout=5.1` filter. Setting the `-mapping_family` option was not necessary.

Note that this is an [upstream bug](https://trac.ffmpeg.org/ticket/5718) that has been open for a while. I completely agree that it should be easy to run this kind of conversion, but I'm not really happy with building in workarounds for broken ffmpeg functionality that should just be fixed upstream.

I can, however, add an option to allow extra (audio) filters to be added before/after normalization.

**Comment by slhck** [comment]
See also https://github.com/slhck/ffmpeg-normalize/issues/67 — this could be solved via such filters.

**Comment by Nottt** [comment]
> So the -mapping_family 1 option should be used automatically for 5.1 input. 

People that know more than me said that I need to use it, and pointed me to that github link. Anyways I think i'd rather be safe than sorry. 

I agree this is a ffmpeg issue, but I don't think they will ever fix this. I just want to encode to opus :/

I don't care about I/O since SSDs are pretty fast nowadays. Whatever you can do is good already thanks.

**Comment by slhck** [comment]
> We can see that they don't put much effort into the OPUS encoder I don't know why....

It's an open-source project and maybe the original maintainer has other priorities now. Anyone's free to propose a patch to fix it, but so far no one has done that, apparently. (I haven't read the issue in detail.)

> I agree this is a ffmpeg issue, but I don't think they will ever fix this. I just want to encode to opus :/

Sure, I can see how at least not being able to provide extra filters is a limitation of my program at this stage. I am really swamped with work and will most likely only get to it in two weeks or so though. Pull requests are welcome though.

**Comment by Nottt** [comment]
I'd love to do PR but I only know bash :/ 

> It's an open-source project and maybe the original maintainer has other priorities now. 

Yeah but ffmpeg is supposed to be the standard to manipulate media files, and with Netflix/Google/Facebook and everyone else using OPUS it's seems strange ffmpeg struggle to do such a simple thing. 

Because of this issue, I've been unable to batch process my files to opus. Maybe google has better developers that can make a bash script around ffmpeg limitations for them to use with youtube... but I'm just the average linux guy 

> I am really swamped with work and will most likely only get to it in two weeks or so though

No problem, thanks for considering it :pray:

**Comment by slhck** [comment]
As a workaround, you could normalize everything to WAV/FLAC using 5.1 and then separately convert the resulting files to Opus with a simple command, using your suggested filters.

**Comment by Nottt** [comment]
Thanks. Will do. 

To be easier for me I'll do that, then run ffmpeg with google settings for vp9 and then merge the output. Huge waste of I/O. I wonder if they use something else for youtube?

Also non related question... I looked into this because when streaming DTS/etc audio with plex the speech sometimes is too low compared to other sounds. 

Will running your script fix this? If the audio 5.1 is downmixed to 2.0 to play in a tv/software/whatever will it keep the normalization? 

If so, it totally worth the effort of doing this. Thank you for the software

**Comment by Nottt** [comment]
Here's my current workaround:

```
#!/bin/bash

# Normalize audio files to pcm

ffmpeg-normalize -vn -sn -cn "$1"

# Extrac desired audios to feed opusenc

ffmpeg -nostdin -i "$1" -map 0:m:language:eng -vn -acodec copy "${1%.mkv}".en.wav

# Encode them with opusenc

opusenc "${1%.mkv}".en.wav "${1%.mkv}".en.mkv
```

When converting to opus after doing loudness normalization is it lost or kept? 

Assuming lossy input, is pcm_s16le lossless? Doing lossy input > pcm_s16le > opus is the same as doing lossy input > opus?

Thanks!

**Comment by slhck** [comment]
The normalization will be kept, yes. And the conversion will not introduce any further loss, as PCM is lossless.

**Comment by slhck** [comment]
You can now specify an additional `channelmap=channel_layout=5.1` filter using the `--pre-filter` option (in version 1.15.0).
